// hexa 8$/hexadash-vue/full-version/src/view/apps/myProfile/overview/UserBio.vue
<template>
  <UserBioBox>
    <sdCards headless>
      <article class="user-info">
        <sdHeading as="h5" class="user-info__title">User Bio</sdHeading>
        <p>
          Nam malesuada dolor tellus pretium amet was hendrerit facilisi id
          vitae enim sed ornare there suspendisse sed orci neque ac sed aliquet
          risus faucibus in pretium molestie nisl tempor quis odio habitant.
        </p>
      </article>
      <address class="user-info">
        <sdHeading as="h5" class="user-info__title">Contact Info</sdHeading>
        <ul class="user-info__contact">
          <li>
            <unicon name="envelope" width="14"></unicon>
            <span>Clayton@example.com</span>
          </li>
          <li>
            <unicon name="phone" width="14"></unicon>
            <span>+44 (0161) 347 8854</span>
          </li>
          <li>
            <unicon name="globe" width="14"></unicon>
            <span>www.example.com</span>
          </li>
        </ul>
      </address>
      <div class="user-info">
        <sdHeading as="h5" class="user-info__title">Skills</sdHeading>
        <div class="user-info__skills">
          <sdButton type="light" outlined class="btn-outlined">
            UI/UX
          </sdButton>
          <sdButton type="light" outlined class="btn-outlined">
            Branding
          </sdButton>
          <sdButton type="light" outlined class="btn-outlined">
            product design
          </sdButton>
          <sdButton type="light" outlined class="btn-outlined">
            web design
          </sdButton>
          <sdButton type="light" outlined class="btn-outlined">
            Application
          </sdButton>
        </div>
      </div>
      <div class="user-info">
        <h5 class="user-info__title">Social Profiles</h5>
        <div class="card__social">
          <a class="btn-icon facebook" to="#">
            <font-awesome-icon
              class="super-crazy-colors"
              :icon="faFacebookF"
              size="1x"
              :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
            />
          </a>
          <a class="btn-icon twitter" to="#">
            <font-awesome-icon
              class="super-crazy-colors"
              :icon="faTwitter"
              size="1x"
              :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
            />
          </a>
          <a class="btn-icon dribble" to="#">
            <font-awesome-icon
              class="super-crazy-colors"
              :icon="faDribbble"
              size="1x"
              :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
            />
          </a>
          <a class="btn-icon instagram" to="#">
            <font-awesome-icon
              class="super-crazy-colors"
              :icon="faInstagram"
              size="1x"
              :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
            />
          </a>
        </div>
      </div>
    </sdCards>
  </UserBioBox>
</template>
<script>
import { UserBioBox } from "./style";
import { defineComponent } from "vue";
import {
  faFacebookF,
  faDribbble,
  faTwitter,
  faInstagram,
  faGithub,
  faMediumM,
} from "@fortawesome/free-brands-svg-icons";

const UserBio = defineComponent({
  name: "UserBio",
  components: { UserBioBox },
  setup() {
    return {
      faFacebookF,
      faDribbble,
      faTwitter,
      faInstagram,
      faGithub,
      faMediumM,
    };
  },
});

export default UserBio;
</script>

// hexa 8$/hexadash-svelte/documentation/src/lib/view/apps/social/widgets/UserBio.svelte
<script>
	import { Card, CardHeader, CardBody } from 'sveltestrap';
	import InlineSVG from 'svelte-inline-svg';

	const contactInfo = [
		{
			icon: 'mail.svg',
			label: 'Clayton@example.com'
		},
		{
			icon: 'phone.svg',
			label: '+44 (0161) 347 8854'
		},
		{
			icon: 'globe.svg',
			label: 'www.example.com'
		}
	];

	const tags = ['UI/UX', 'Branding', 'Product Design', 'Application', 'Web Design'];
	const socials = ['facebook-f', 'twitter', 'dribbble', 'instagram'];
</script>

<Card class="mb-25">
	<div class="user-bio border-bottom">
		<CardHeader class="border-bottom-0 pt-sm-30 pb-sm-0 px-md-25 px-3">
			<div class="profile-header-title">User Bio</div>
		</CardHeader>
		<CardBody class="pt-md-1 pt-0">
			<div class="user-bio__content">
				<p class="m-0">
					Nam malesuada dolor tellus pretium amet was hendrerit facilisi id vitae enim sed ornare
					there suspendisse sed orci neque ac sed aliquet risus faucibus in pretium molestie nisl
					tempor quis odio habitant.
				</p>
			</div>
		</CardBody>
	</div>
	<div class="user-info border-bottom">
		<CardHeader class="border-bottom-0 pt-sm-25 pb-sm-0 px-md-25 px-3">
			<div class="profile-header-title">Contact info</div>
		</CardHeader>
		<CardBody class="pt-md-1 pt-0">
			<div class="user-content-info">
				{#each contactInfo as info}
					<p class="user-content-info__item">
						<InlineSVG src={`/img/svg/${info.icon}`} />
						{info.label}
					</p>
				{/each}
			</div>
		</CardBody>
	</div>
	<div class="user-skils border-bottom">
		<CardHeader class="border-bottom-0 pt-sm-25 pb-sm-0 px-md-25 px-3">
			<div class="profile-header-title">Skills</div>
		</CardHeader>
		<CardBody class="pt-md-1 pt-0">
			<ul class="user-skils-parent">
				{#each tags as tag}
					<li class="user-skils-parent__item">
						<a href={'#'}>{tag}</a>
					</li>
				{/each}
			</ul>
		</CardBody>
	</div>
	<div class="db-social">
		<CardHeader class="border-bottom-0 pt-sm-25 pb-sm-0 px-md-25 px-3">
			<div class="profile-header-title">Social Profiles</div>
		</CardHeader>
		<CardBody class="pt-md-1 pt-0">
			<ul class="db-social-parent mb-0">
				{#each socials as icon}
					<li class="db-social-parent__item">
						<a class="color-{icon} hover-{icon} wh-44 fs-18" href={'#'}>
							<i class="lab la-{icon}" />
						</a>
					</li>
				{/each}
			</ul>
		</CardBody>
	</div>
</Card>
