// hexa 8$/hexadash-typescript-vue/full-version/src/components/cards/frame/CardsFrame.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { CardFrame } from './style';

export default defineComponent({
  name: 'Cards',
  components: {
    CardFrame,
  },
  props: {
    title: [String, Object, Node],
    size: {
      type: String,
      default: 'default',
    },
    more: {
      type: Boolean,
      default: false,
    },
    bodyStyle: Object,
    headStyle: Object,
    headless: {
      type: Boolean,
      default: false,
    },
    border: {
      type: Boolean,
      default: false,
    },
    caption: String,
    bodypadding: String,
    moreText: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<template>
  <CardFrame
    v-if="!headless"
    :cardSize="size"
    :title="title"
    :bodyStyle="bodyStyle"
    :headStyle="headStyle"
    :bordered="border"
    :bodypadding="bodypadding"
    :style="{ width: '100%' }"
  >
    <template #title>
      <slot name="title" />
    </template>
    <slot name="caption" />
    <template v-slot:extra>
      <slot name="button" />
      <sdDropdown v-if="more" :action="['click']" placement="bottomRight">
        <template v-slot:overlay>
          <slot name="more" />
        </template>
        <router-link class="card-extra-link" v-if="!moreText" to="#"
          ><unicon name="ellipsis-h" width="24"></unicon
        ></router-link>
        <router-link v-else to="#">More</router-link>
      </sdDropdown>
    </template>
    <slot />
  </CardFrame>

  <CardFrame
    :bodypadding="bodypadding"
    :bodyStyle="bodyStyle"
    :cardSize="size"
    :style="{ width: '100%' }"
    :bordered="border"
    :headless="true"
    v-else
  >
    <sdHeading v-if="title" as="h4">{{ title }}</sdHeading>
    <p v-if="caption">{{ caption }}</p>
    <slot />
  </CardFrame>
</template>

// hexa 8$/hexadash-react/documentation/src/components/cards/frame/cards-frame.js
import React from 'react';
import { Link } from 'react-router-dom';
import UilellipsisH from '@iconscout/react-unicons/icons/uil-ellipsis-h';
import PropTypes from 'prop-types';
import { CardFrame } from './style';
import Heading from '../../heading/heading';
import { Dropdown } from '../../dropdown/dropdown';

const Cards = props => {
  const {
    title,
    children,
    more,
    moreText,
    size,
    headless,
    caption,
    isbutton,
    bodyStyle,
    headStyle,
    border,
    bodypadding,
    className,
  } = props;
  return (
    <>
      {!headless ? (
        <CardFrame
          size={size}
          title={title}
          bodyStyle={bodyStyle && bodyStyle}
          headStyle={headStyle && headStyle}
          bordered={border}
          className={className}
          bodypadding={bodypadding && bodypadding}
          extra={
            <>
              {more && (
                <Dropdown content={more} placement="bottom">
                  <Link onClick={e => e.preventDefault()} to="#">
                    {!moreText ? <UilellipsisH /> : 'More'}
                  </Link>
                </Dropdown>
              )}

              {isbutton && isbutton}
            </>
          }
          style={{ width: '100%' }}
        >
          {children}
        </CardFrame>
      ) : (
        <CardFrame
          bodypadding={bodypadding && bodypadding}
          bodyStyle={bodyStyle && bodyStyle}
          size={size}
          style={{ width: '100%' }}
          bordered={border}
          className={className}
        >
          {title && <Heading as="h4">{title}</Heading>}
          {caption && <p>{caption}</p>}
          {children}
        </CardFrame>
      )}
    </>
  );
};

Cards.defaultProps = {
  border: false,
};

Cards.propTypes = {
  title: PropTypes.oneOfType([PropTypes.string, PropTypes.object, PropTypes.node]),
  size: PropTypes.string,
  more: PropTypes.oneOfType([PropTypes.string, PropTypes.object, PropTypes.node]),
  bodyStyle: PropTypes.object,
  headStyle: PropTypes.object,
  isbutton: PropTypes.node,
  headless: PropTypes.bool,
  border: PropTypes.bool,
  caption: PropTypes.string,
  bodypadding: PropTypes.string,
  className: PropTypes.string,
  moreText: PropTypes.bool,
  children: PropTypes.oneOfType([PropTypes.object, PropTypes.string, PropTypes.node]),
};

export { Cards };
