// hexa 8$/hexadash-react/documentation/src/container/pages/overview/UserCard.js
import React from 'react';
import UilEnvelope from '@iconscout/react-unicons/icons/uil-envelope';
import UilUserPlus from '@iconscout/react-unicons/icons/uil-user-plus';
import { Link } from 'react-router-dom';
import PropTypes from 'prop-types';
import { Col, Row } from 'antd';
import { UserCard } from '../style';
import Heading from '../../../components/heading/heading';
import { Cards } from '../../../components/cards/frame/cards-frame';
import { Button } from '../../../components/buttons/buttons';

const UserCards = ({ user }) => {
  const { name, designation, img } = user;
  return (
    <UserCard>
      <div className="card user-card">
        <Cards headless>
          <figure>
            <img src={require(`../../../${img}`)} alt="" />
          </figure>
          <figcaption>
            <div className="card__content">
              <Heading className="card__name" as="h6">
                <Link to="#">{name}</Link>
              </Heading>
              <p className="card__designation">{designation}</p>
            </div>

            <div className="card__actions">
              <Button size="default" type="white">
                <UilEnvelope />
                Message
              </Button>
              <Button size="default" type="white">
                <UilUserPlus />
                Following
              </Button>
            </div>
            <div className="card__info">
              <Row gutter={15}>
                <Col xs={8}>
                  <div className="info-single">
                    <Heading className="info-single__title" as="h2">
                      $72,572
                    </Heading>
                    <p>Total Revenue</p>
                  </div>
                </Col>
                <Col xs={8}>
                  <div className="info-single">
                    <Heading className="info-single__title" as="h2">
                      3,257
                    </Heading>
                    <p>Orders</p>
                  </div>
                </Col>
                <Col xs={8}>
                  <div className="info-single">
                    <Heading className="info-single__title" as="h2">
                      74
                    </Heading>
                    <p>Products</p>
                  </div>
                </Col>
              </Row>
            </div>
          </figcaption>
        </Cards>
      </div>
    </UserCard>
  );
};

UserCards.propTypes = {
  user: PropTypes.object,
};

export default UserCards;

// hexa 8$/hexadash-vue/full-version/src/view/pages/overview/UserCard.vue
<template>
  <sdUserCard>
    <div class="card user-card">
      <sdCards headless>
        <figure>
          <img :src="require(`@/${user.img}`)" alt="" />
        </figure>
        <figcaption>
          <div class="card__content">
            <sdHeading class="card__name" as="h6">
              <a to="#">{{ user.name }}</a>
            </sdHeading>
            <p class="card__designation">{{ user.designation }}</p>
          </div>

          <div class="card__actions">
            <sdButton size="default" type="white" outlined>
              <unicon name="envelope" width="14"></unicon>
              <span>Message</span>
            </sdButton>
            <sdButton size="default" type="white" outlined>
              <unicon name="user-plus" width="14"></unicon>
              <span>Following</span>
            </sdButton>
          </div>
          <div class="card__info">
            <a-row :gutter="15">
              <a-col :xs="8">
                <div class="info-single">
                  <sdHeading class="info-single__title" as="h2">
                    $72,572
                  </sdHeading>
                  <p>Total Revenue</p>
                </div>
              </a-col>
              <a-col :xs="8">
                <div class="info-single">
                  <sdHeading class="info-single__title" as="h2">
                    3,257
                  </sdHeading>
                  <p>Orders</p>
                </div>
              </a-col>
              <a-col :xs="8">
                <div class="info-single">
                  <sdHeading class="info-single__title" as="h2"> 74 </sdHeading>
                  <p>Products</p>
                </div>
              </a-col>
            </a-row>
          </div>
        </figcaption>
      </sdCards>
    </div>
  </sdUserCard>
</template>
<script>
import PropTypes from "vue-types";
import { defineComponent } from "vue";

const UserCards = defineComponent({
  name: "UserCards",
  props: {
    user: PropTypes.object,
  },
  setup() {
    // return { UserCard };
  },
});

export default UserCards;
</script>
