// hexa 8$/hexadash-react/documentation/src/container/pages/AxiosIntegration.js
import { Col, Row } from 'antd';
import Prism from "prismjs";
import { useEffect } from 'react';
import { Cards } from '../../components/cards/frame/cards-frame';
import { PageHeader } from '../../components/page-headers/page-headers';
import { Main } from '../styled';
import { DocumentationStyleWrap } from './style';

const Navigation = () => {
  const PageRoutes = [
    {
        path: 'index',
        breadcrumbName: 'Docs',
    },
    {
        path: '',
        breadcrumbName: 'Axios Integration',
    },
  ];
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <>
      <PageHeader className="ninjadash-page-header-main" title="Axios Integration" routes={PageRoutes} />
      <Main>
        <DocumentationStyleWrap>
          <Row gutter={25}>
            <Col md={18} xs={24}>
              <Cards headless>
                <div className="ninjadash-template-documentation">
                    <h2>Axios CRUD Integration</h2>
                    <p> HexaDash provide you a ready setup for Axios CRUD integration using REST API </p>
                    <h2>Update API Base URL</h2>
                    <p className="mb-0">From <code>.env</code> file you can update the base URL</p>
                    <div className="docs-highlighter">
                        <pre>
                            <code className="language-javascript">
{
`
REACT_APP_BASE_URL = "YOUR_API_BASE_URL"
`
}
                            </code>
                        </pre>
                    </div>
                </div>
              </Cards>
              <Cards headless>
                <div className="ninjadash-template-documentation">
                    <h2>Axios Setup</h2>
                    <p>Then we create Axios Instance. we can find the instancees for <strong>GET,</strong> <strong>POST,</strong> <strong>PATCH,</strong> <strong>PUT</strong> at <code>src/config/dataService/dataService.js</code>.</p>
                    <h2>Redux Setup</h2>
                    <p className="mb-0">After the avobe setup we will do our redux setup.</p>
                    <p className="mb-0">At first create actio to <code>/src/redux/crud/axios/actionCreator.js</code>.</p>
                    <div className="docs-highlighter mb-35">
                        <pre>
                            <code className="language-javascript">
{
`
import actions from './actions';
import { DataService } from '../../../config/dataService/dataService';

const {
  axiosAddBegin,
  axiosAddSuccess,
  axiosAddErr
} = actions;
const axiosDataSubmit = data => {
  return async dispatch => {
    try {
      await dispatch(axiosAddBegin());
      const response = await DataService.post('/store', data);
      await dispatch(axiosAddSuccess(response.data.data));
      await addNotificationSuccess();
    } catch (err) {
      await dispatch(axiosAddErr(err));
      await addNotificationError(err);
    }
  };
};
export {
  axiosDataSubmit,
};
`
}
                            </code>
                        </pre>
                    </div>
                    <p className="mb-0">Then we add action at <code>/src/redux/crud/axios/action.js</code>.</p>
                    <div className="docs-highlighter mb-35">
                        <pre>
                            <code className="language-javascript">
{
`
const actions = {
  AXIOS_ADD_BEGIN: 'AXIOS_ADD_BEGIN',
  AXIOS_ADD_SUCCESS: 'AXIOS_ADD_SUCCESS',
  AXIOS_ADD_ERR: 'AXIOS_ADD_ERR',

  axiosAddBegin: () => {
    return {
      type: actions.AXIOS_ADD_BEGIN,
    };
  },

  axiosAddSuccess: data => {
    return {
      type: actions.AXIOS_ADD_SUCCESS,
      data,
    };
  },

  axiosAddErr: err => {
    return {
      type: actions.AXIOS_ADD_ERR,
      err,
    };
  },
};

export default actions;

`
}
                            </code>
                        </pre>
                    </div>
                    <p className="mb-0">Then we add reducer at <code>/src/redux/crud/axios/reducers.js</code>.</p>
                    <div className="docs-highlighter mb-35">
                        <pre>
                            <code className="language-javascript">
{
`
import actions from './actions';

const {
  AXIOS_ADD_BEGIN,
  AXIOS_ADD_SUCCESS,
  AXIOS_ADD_ERR,
} = actions;

const initialState = {
  data: [],
  url: null,
  fileLoading: false,
  loading: false,
  error: null,
};

const initialStateSingle = {
  data: null,
  loading: false,
  error: null,
};

const axiosCrudReducer = (state = initialState, action) => {
  const { type, data, err } = action;
  switch (type) {
    case AXIOS_ADD_BEGIN:
      return {
        ...state,
        loading: true,
      };

    case AXIOS_ADD_SUCCESS:
      return {
        ...state,
        data,
        error: false,
        loading: false,
      };

    case AXIOS_ADD_ERR:
      return {
        ...state,
        error: err,
        loading: false,
      };

    default:
      return state;
  }
};

export { axiosCrudReducer };

`
}
                            </code>
                        </pre>
                    </div>
                    <p className="mb-0">After configuring redux you just need to call the action your component</p>
                    <div className="docs-highlighter">
                        <pre>
                            <code className="language-javascript">
{
`
import React, { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { axiosDataSubmit } from '../../../redux/crud/axios/actionCreator';

const AddNew = () => {
  const dispatch = useDispatch();
  const { isLoading, url, isFileLoading } = useSelector(state => {
    return {
      url: state.AxiosCrud.url,
    };
  });
  const {pathname} = useLocation();
  const [form] = Form.useForm();

  const [state, setState] = useState({
    join: '',
  });

  const handleSubmit = values => {
    dispatch(
      axiosDataSubmit({
        ...values,
        image: url,
        join: state.join,
        id: new Date().getTime(),
      }),
    );
    form.resetFields();
    dispatch(axiosFileClear());
  };

`
}
                            </code>
                        </pre>
                    </div>
                </div>
              </Cards>
            </Col>
          </Row>
        </DocumentationStyleWrap>

      </Main>
    </>
  );
};

export default Navigation;

// hexa 8$/hexadash-typescript-vue/documentation/src/view/pages/AxiosIntegration.vue
<template>
  <div>
    <sdPageHeader
      title="Axios Integration"
      class="ninjadash-page-header-main"
      :routes="PageRoutes"
    >
    </sdPageHeader>
    <Main>
      <DocumentationStyleWrap>
        <a-row :gutter="25">
          <a-col :sm="24" :xs="24">
            <sdCards headless>
              <div class="ninjadash-template-documentation">
                <h2>Axios CRUD Integration</h2>
                <p>
                  HexaDash provides you a ready-maid setup for Axios CRUD integration
                  using REST API
                </p>
                <h2>Update API Base URL</h2>
                <p class="mb-0">
                  From <code>.env</code> file you can update the base URL
                </p>

                <prism-editor
                  :readonly="true"
                  class="my-editor height-100"
                  v-model="baseUrl"
                  :highlight="highlighter"
                ></prism-editor>
              </div>
            </sdCards>
            <sdCards headless>
              <div class="ninjadash-template-documentation">
                <h2>Axios Setup</h2>
                <p>
                  Then we create Axios Instance. we can find the instancees for
                  <strong>GET,</strong> <strong>POST,</strong>
                  <strong>PATCH,</strong> <strong>PUT</strong> at
                  <code>src/config/dataService/dataService.ts</code>.
                </p>
                <h2>Redux Setup</h2>
                <p class="mb-0">
                  After the above setup we will do our Vuex setup.
                </p>
                <p class="mb-0">
                  At first create action in
                  <code>/src/vuex/modules/crud/axios/actionCreator.ts</code> file.
                </p>
                <prism-editor
                  :readonly="true"
                  class="my-editor height-100"
                  v-model="vuexData"
                  :highlight="highlighter"
                ></prism-editor>
                <p class="mb-0">
                  After configuring Vuex you need to call the action in your
                  component
                </p>
                <prism-editor
                  :readonly="true"
                  class="my-editor height-100"
                  v-model="component"
                  :highlight="highlighter"
                ></prism-editor>
              </div>
            </sdCards>
          </a-col>
        </a-row>
      </DocumentationStyleWrap>
    </Main>
  </div>
</template>

<script>
import { Main } from "../styled";
import { defineComponent, ref } from "vue";

import { PrismEditor } from "vue-prism-editor";
import "vue-prism-editor/dist/prismeditor.min.css";
import { highlight, languages } from "prismjs/components/prism-core";
import "prismjs/components/prism-clike";
import "prismjs/components/prism-javascript";
import "prismjs/themes/prism-tomorrow.css";
import { DocumentationStyleWrap } from "./style";

const PageRoutes = [
  {
    path: "index",
    breadcrumbName: "Docs",
  },
  {
    path: "",
    breadcrumbName: "Axios Integration",
  },
];

export default defineComponent({
  name: "Axios",
  components: {
    Main,
    PrismEditor,
    DocumentationStyleWrap,
  },
  setup() {
    const baseUrl = ref(`
VITE_BASE_URL = "YOUR_API_BASE_URL"
`);

    const vuexData = ref(`
import mutations from './mutations';
import { DataService } from '@/config/dataService/dataService';

const state = () => ({
  data: [],
  loading: false,
  error: null,
});

const actions = {

  async axiosCrudGetData({ commit }) {
    try {
      await commit('axiosReadBegin');
      const query = await DataService.get('/all');
      await commit('axiosReadSuccess', query.data.data);
    } catch (err) {
      console.log(err);
      await commit('axiosReadErr', err);
    }
  },
};

`);

    const component = ref(`
import { useStore } from "vuex";
import { computed, onMounted, ref, reactive, defineComponent } from "vue";

const ViewPage = defineComponent({
  name: "ViewPage",
  setup() {
    const { state, dispatch } = useStore();
    const data = computed(() => state.crud.data);
    const isLoading = computed(() => state.crud.loading);
    onMounted(() => {
      dispatch("axiosCrudGetData");
    });

    return {
      data,
      isLoading,
    };
  },
});
export default ViewPage;
`);

    return {
      baseUrl,
      PageRoutes,
      vuexData,
      component,
    };
  },
  methods: {
    highlighter(code) {
      return highlight(code, languages.js); //returns html
    },
  },
});
</script>
