// hexa 8$/hexadash-react/documentation/src/components/tabs/tabs.js
import React from 'react';
import * as Unicons from '@iconscout/react-unicons';
import PropTypes from 'prop-types';
import { TabBasic, Child } from './style';
const Tab = props => {
  const { data, tabPosition, type, color } = props;
  let counter = 0;

  return (
    <TabBasic className={`ninjadash-tab-${type}`} color={color && color} defaultActiveKey="1" tabPosition={tabPosition !== undefined ? tabPosition : 'top'}>
      {data.map(item => {
        const { title, content, icon, tabTitle } = item;
        const IconTag = Unicons[icon];
        counter += 1;
        return (
          <Child
            color={color && color}
            tab={
              icon === undefined ? (
                tabTitle
              ) : (
                <span>
                  <IconTag />
                  {tabTitle}
                </span>
              )
            }
            key={counter}
          >
            <h2>{title}</h2>
            <p>{content}</p>
          </Child>
        );
      })}
    </TabBasic>
  );
};

Tab.propTypes = {
  color: PropTypes.string,
  type: PropTypes.string,
  tabPosition: PropTypes.string,
  data: PropTypes.arrayOf(PropTypes.object),
};

export { Tab };

// hexa 8$/hexadash-typescript-vue/full-version/src/components/tabs/Tabs.vue
<template>
  <TabBasic
    v-model:activeKey="activeKey"
    :color="color && color"
    :tabPosition="tabPosition !== undefined ? tabPosition : 'top'"
  >
    <Child v-for="(item, index) in data" :key="index + 1" :color="color && color">
      <template #tab>
        <span v-if="item.icon && item.icon !== 'undefined'">
          <unicon :name="item.icon" width="18"></unicon>
          <span>{{ item.tabTitle }}</span>
        </span>
        <span v-if="!item.icon">
          {{ item.tabTitle }}
        </span>
      </template>
      <h2>{{ item.title }}</h2>
      <p>{{ item.content }}</p>
    </Child>
  </TabBasic>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import type { PropType } from 'vue';
import { TabBasic, Child } from './Style';

const props = defineProps({
  color: String,
  tabPosition: {
    type: String,
    validator: (value) => ['top', 'right', 'bottom', 'left'].includes(value as string),
    default: 'top',
  },
  data: {
    type: Array as PropType<{ title: string; content: string; icon?: string; tabTitle: string }[]>,
    required: true,
  },
});
let activeKey = ref(1);
</script>
