// hexa 8$/hexadash-react/documentation/src/container/project/overview/TaskList.js
import React, { useState } from 'react';
import UilEye from '@iconscout/react-unicons/icons/uil-eye';
import UilEdit from '@iconscout/react-unicons/icons/uil-edit';
import UilPlus from '@iconscout/react-unicons/icons/uil-plus';
import UilTrashAlt from '@iconscout/react-unicons/icons/uil-trash-alt';
import UilEllipsisH from '@iconscout/react-unicons/icons/uil-ellipsis-h';
import UilExpandArrows from '@iconscout/react-unicons/icons/uil-expand-arrows';
import { Table } from 'antd';
import { Link } from 'react-router-dom';
import { Button } from '../../../components/buttons/buttons';
import { Dropdown } from '../../../components/dropdown/dropdown';
import { TasklistAction } from '../style';

const TaskList = () => {
  const [state, setState] = useState({
    selectedRowKeys: [],
    selectedRows: [],
  });
  const dataSource = [
    {
      key: '1',
      title: <span className="task-title">Add Images To the gallery</span>,
      component: (
        <TasklistAction>
          <span className="task-created">09:20 AM </span>
          <img
            className="task-author"
            style={{ width: '30px' }}
            src={require('../../../static/img/users/1.png')}
            alt=""
          />
          <span className="task-move">
            <UilExpandArrows />
          </span>
          <div className="task-action">
            <Dropdown
              content={
                <>
                  <Link to="#">
                    <UilEye />
                    View
                  </Link>
                  <Link to="#">
                    <UilEdit />
                    Edit
                  </Link>
                  <Link to="#">
                    <UilTrashAlt />
                    Delete
                  </Link>
                </>
              }
            >
              <Link to="#">
                <UilEllipsisH />
              </Link>
            </Dropdown>
          </div>
        </TasklistAction>
      ),
    },
    {
      key: '2',
      title: <span className="task-title">Add Images To the gallery</span>,
      component: (
        <TasklistAction>
          <span className="task-created">09:20 AM </span>
          <img
            className="task-author"
            style={{ width: '30px' }}
            src={require('../../../static/img/users/1.png')}
            alt=""
          />
          <span className="task-move">
            <UilExpandArrows />
          </span>
          <div className="task-action">
            <Dropdown
              content={
                <>
                  <Link to="#">
                    <UilEye />
                    View
                  </Link>
                  <Link to="#">
                    <UilEdit />
                    Edit
                  </Link>
                  <Link to="#">
                    <UilTrashAlt />
                    Delete
                  </Link>
                </>
              }
            >
              <Link to="#">
                <UilEllipsisH />
              </Link>
            </Dropdown>
          </div>
        </TasklistAction>
      ),
    },
    {
      key: '3',
      title: <span className="task-title">Add Images To the gallery</span>,
      component: (
        <TasklistAction>
          <span className="task-created">09:20 AM </span>
          <img
            className="task-author"
            style={{ width: '30px' }}
            src={require('../../../static/img/users/1.png')}
            alt=""
          />
          <span className="task-move">
            <UilExpandArrows />
          </span>
          <div className="task-action">
            <Dropdown
              content={
                <>
                  <Link to="#">
                    <UilEye />
                    View
                  </Link>
                  <Link to="#">
                    <UilEdit />
                    Edit
                  </Link>
                  <Link to="#">
                    <UilTrashAlt />
                    Delete
                  </Link>
                </>
              }
            >
              <Link to="#">
                <UilEllipsisH />
              </Link>
            </Dropdown>
          </div>
        </TasklistAction>
      ),
    },
    {
      key: '4',
      title: <span className="task-title">Add Images To the gallery</span>,
      component: (
        <TasklistAction>
          <span className="task-created">09:20 AM </span>
          <img
            className="task-author"
            style={{ width: '30px' }}
            src={require('../../../static/img/users/1.png')}
            alt=""
          />
          <span className="task-move">
            <UilExpandArrows />
          </span>
          <div className="task-action">
            <Dropdown
              content={
                <>
                  <Link to="#">
                    <UilEye />
                    View
                  </Link>
                  <Link to="#">
                    <UilEdit />
                    Edit
                  </Link>
                  <Link to="#">
                    <UilTrashAlt />
                    Delete
                  </Link>
                </>
              }
            >
              <Link to="#">
                <UilEllipsisH />
              </Link>
            </Dropdown>
          </div>
        </TasklistAction>
      ),
    },
    {
      key: '5',
      title: <span className="task-title">Add Images To the gallery</span>,
      component: (
        <TasklistAction>
          <span className="task-created">09:20 AM </span>
          <img
            className="task-author"
            style={{ width: '30px' }}
            src={require('../../../static/img/users/1.png')}
            alt=""
          />
          <span className="task-move">
            <UilExpandArrows />
          </span>
          <div className="task-action">
            <Dropdown
              content={
                <>
                  <Link to="#">
                    <UilEye />
                    View
                  </Link>
                  <Link to="#">
                    <UilEdit />
                    Edit
                  </Link>
                  <Link to="#">
                    <UilTrashAlt />
                    Delete
                  </Link>
                </>
              }
            >
              <Link to="#">
                <UilEllipsisH />
              </Link>
            </Dropdown>
          </div>
        </TasklistAction>
      ),
    },
    {
      key: '6',
      title: <span className="task-title">Add Images To the gallery</span>,
      component: (
        <TasklistAction>
          <span className="task-created">09:20 AM </span>
          <img
            className="task-author"
            style={{ width: '30px' }}
            src={require('../../../static/img/users/1.png')}
            alt=""
          />
          <span className="task-move">
            <UilExpandArrows />
          </span>
          <div className="task-action">
            <Dropdown
              content={
                <>
                  <Link to="#">
                    <UilEye />
                    View
                  </Link>
                  <Link to="#">
                    <UilEdit />
                    Edit
                  </Link>
                  <Link to="#">
                    <UilTrashAlt />
                    Delete
                  </Link>
                </>
              }
            >
              <Link to="#">
                <UilEllipsisH />
              </Link>
            </Dropdown>
          </div>
        </TasklistAction>
      ),
    },
  ];

  const columns = [
    {
      dataIndex: 'title',
      key: 'title',
    },
    {
      dataIndex: 'component',
      key: 'component',
    },
  ];

  const rowSelection = {
    onChange: (selectedRowKeys, selectedRows) => {
      setState({ ...state, selectedRowKeys, selectedRows });
    },
    getCheckboxProps: record => ({
      disabled: record.name === 'Disabled User', // Column configuration not to be checked
      name: record.name,
    }),
  };

  return (
    <div className="task-list-inner table-responsive">
      <Table pagination={false} rowSelection={rowSelection} dataSource={dataSource} columns={columns} />
      <div className="tasklist-action">
        <Button type="primary" size="large" transparented>
          <UilPlus /> Add New Task
        </Button>
      </div>
    </div>
  );
};

export default TaskList;

// hexa 8$/hexadash-typescript-vue/full-version/src/views/apps/project/overview/TaskList.vue
<script setup lang="tsx">
import { TasklistAction } from '../style';
import { ref } from 'vue';

const selectedRowKeys = ref([]);
const selectedRows = ref([]);
const dataSource = [
  {
    key: '1',
    title: <span class="task-title">Add Images To the gallery</span>,
    component: (
      <TasklistAction>
        <span class="task-created">09:20 AM </span>
        <img class="task-author" style={{ width: '30px' }} src={'/src/assets/img/users/1.png'} alt="" />
        <span class="task-move">
          <unicon name="expand-arrows" width="16"></unicon>
        </span>
        <div class="task-action">
          <sdDropdown
            overlay={
              <>
                <a to="#">
                  <unicon name="eye" width="14"></unicon>
                  View
                </a>
                <a to="#">
                  <unicon name="edit" width="14"></unicon>
                  Edit
                </a>
                <a to="#">
                  <unicon name="trash-alt" width="14"></unicon>
                  Delete
                </a>
              </>
            }
          >
            <a to="#">
              <unicon name="ellipsis-h" width="16"></unicon>
            </a>
          </sdDropdown>
        </div>
      </TasklistAction>
    ),
  },
  {
    key: '2',
    title: <span class="task-title">Add Images To the gallery</span>,
    component: (
      <TasklistAction>
        <span class="task-created">09:20 AM </span>
        <img class="task-author" style={{ width: '30px' }} src={'/src/assets/img/users/1.png'} alt="" />
        <span class="task-move">
          <unicon name="expand-arrows" width="16"></unicon>
        </span>
        <div class="task-action">
          <sdDropdown
            overlay={
              <>
                <a to="#">
                  <unicon name="eye" width="14"></unicon>
                  View
                </a>
                <a to="#">
                  <unicon name="edit" width="14"></unicon>
                  Edit
                </a>
                <a to="#">
                  <unicon name="trash-alt" width="14"></unicon>
                  Delete
                </a>
              </>
            }
          >
            <a to="#">
              <unicon name="ellipsis-h" width="16"></unicon>
            </a>
          </sdDropdown>
        </div>
      </TasklistAction>
    ),
  },
  {
    key: '3',
    title: <span class="task-title">Add Images To the gallery</span>,
    component: (
      <TasklistAction>
        <span class="task-created">09:20 AM </span>
        <img class="task-author" style={{ width: '30px' }} src={'/src/assets/img/users/1.png'} alt="" />
        <span class="task-move">
          <unicon name="expand-arrows" width="16"></unicon>
        </span>
        <div class="task-action">
          <sdDropdown
            overlay={
              <>
                <a to="#">
                  <unicon name="eye" width="14"></unicon>
                  View
                </a>
                <a to="#">
                  <unicon name="edit" width="14"></unicon>
                  Edit
                </a>
                <a to="#">
                  <unicon name="trash-alt" width="14"></unicon>
                  Delete
                </a>
              </>
            }
          >
            <a to="#">
              <unicon name="ellipsis-h" width="16"></unicon>
            </a>
          </sdDropdown>
        </div>
      </TasklistAction>
    ),
  },
  {
    key: '4',
    title: <span class="task-title">Add Images To the gallery</span>,
    component: (
      <TasklistAction>
        <span class="task-created">09:20 AM </span>
        <img class="task-author" style={{ width: '30px' }} src={'/src/assets/img/users/1.png'} alt="" />
        <span class="task-move">
          <unicon name="expand-arrows" width="16"></unicon>
        </span>
        <div class="task-action">
          <sdDropdown
            overlay={
              <>
                <a to="#">
                  <unicon name="eye" width="14"></unicon>
                  View
                </a>
                <a to="#">
                  <unicon name="edit" width="14"></unicon>
                  Edit
                </a>
                <a to="#">
                  <unicon name="trash-alt" width="14"></unicon>
                  Delete
                </a>
              </>
            }
          >
            <a to="#">
              <unicon name="ellipsis-h" width="16"></unicon>
            </a>
          </sdDropdown>
        </div>
      </TasklistAction>
    ),
  },
  {
    key: '5',
    title: <span class="task-title">Add Images To the gallery</span>,
    component: (
      <TasklistAction>
        <span class="task-created">09:20 AM </span>
        <img class="task-author" style={{ width: '30px' }} src={'/src/assets/img/users/1.png'} alt="" />
        <span class="task-move">
          <unicon name="expand-arrows" width="16"></unicon>
        </span>
        <div class="task-action">
          <sdDropdown
            overlay={
              <>
                <a to="#">
                  <unicon name="eye" width="14"></unicon>
                  View
                </a>
                <a to="#">
                  <unicon name="edit" width="14"></unicon>
                  Edit
                </a>
                <a to="#">
                  <unicon name="trash-alt" width="14"></unicon>
                  Delete
                </a>
              </>
            }
          >
            <a to="#">
              <unicon name="ellipsis-h" width="16"></unicon>
            </a>
          </sdDropdown>
        </div>
      </TasklistAction>
    ),
  },
  {
    key: '6',
    title: <span class="task-title">Add Images To the gallery</span>,
    component: (
      <TasklistAction>
        <span class="task-created">09:20 AM </span>
        <img class="task-author" style={{ width: '30px' }} src={'/src/assets/img/users/1.png'} alt="" />
        <span class="task-move">
          <unicon name="expand-arrows" width="16"></unicon>
        </span>
        <div class="task-action">
          <sdDropdown
            overlay={
              <>
                <a to="#">
                  <unicon name="eye" width="14"></unicon>
                  View
                </a>
                <a to="#">
                  <unicon name="edit" width="14"></unicon>
                  Edit
                </a>
                <a to="#">
                  <unicon name="trash-alt" width="14"></unicon>
                  Delete
                </a>
              </>
            }
          >
            <a to="#">
              <unicon name="ellipsis-h" width="16"></unicon>
            </a>
          </sdDropdown>
        </div>
      </TasklistAction>
    ),
  },
];
const columns = [
  {
    dataIndex: 'title',
    key: 'title',
  },
  {
    dataIndex: 'component',
    key: 'component',
  },
];

const rowSelection = {
  onChange: (selectedRowKeys: any, selectedRows: any) => {
    selectedRowKeys.value = selectedRows;
  },
  getCheckboxProps: (record: any) => ({
    disabled: record.name === 'Disabled User',
    name: record.name,
  }),
};
</script>

<template>
  <div class="task-list-inner table-responsive">
    <a-table :pagination="false" :rowSelection="rowSelection" :dataSource="dataSource" :columns="columns" />
    <div class="tasklist-action">
      <sdButton type="primary" size="lg" transparented>
        <unicon name="plus" width="14"></unicon> Add New Task
      </sdButton>
    </div>
  </div>
</template>
