// hexa 8$/hexadash-typescript-vue/full-version/src/components/alerts/Alerts.vue
<template>
  <Style
    :message="message"
    :type="type"
    :description="description"
    :closable="closable && closable"
    :showIcon="showIcon && showIcon"
    :outlined="outlined"
    :closeText="closeText && closeText"
  >
    <template v-slot:description>
      <div>
        <slot name="description"></slot>
      </div>
    </template>
  </Style>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Style } from './styled';

export default defineComponent({
  name: 'Alerts',
  components: {
    Style,
  },
  props: {
    type: {
      type: String,
      validation: (value: any) => ['success', 'info', 'warning', 'error'].includes(value as string),
      default: 'success',
    },
    message: {
      type: String,
      default: 'Hello there! A simple success alert—check it out!',
    },
    description: String,
    showIcon: {
      type: Boolean,
      default: false,
    },
    outlined: {
      type: Boolean,
      default: false,
    },
    closable: {
      type: Boolean,
      default: false,
    },
    closeText: String,
    icon: Node,
  },
});
</script>

// hexa 8$/hexadash-react/documentation/src/components/alerts/alerts.js
import React from 'react';
import PropTypes from 'prop-types';
import { AlertWrap } from './Style';

const Alert = props => {
  const { type, icon, message, description, showIcon, outlined, closable, closeText } = props;

  return (
    <AlertWrap
      message={message}
      type={type}
      description={description}
      closable={closable}
      showIcon={showIcon && showIcon}
      outlined={outlined}
      closeText={closeText && closeText}
      icon={icon && icon}
    />
  );
};

Alert.defaultProps = {
  type: 'success',
  message: 'Hello there! A simple success alert—check it out!',
};

Alert.propTypes = {
  type: PropTypes.oneOf(['success', 'info', 'warning', 'error']),
  message: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  description: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  showIcon: PropTypes.bool,
  outlined: PropTypes.bool,
  closable: PropTypes.bool,
  closeText: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  icon: PropTypes.node,
};

export default Alert;
