// hexa 8$/hexadash-typescript-vue/full-version/src/components/cards/OverviewCardMesh.vue
<script setup lang="ts">
import { OverviewCardMeshWrap } from './style';
import { onMounted, ref } from 'vue';
import Vue3Autocounter from 'vue3-autocounter';

const props = defineProps({
  data: {
    type: Object,
  },
});

const didViewCountUp = ref(false);

onMounted(() => {
  setTimeout(() => {
    didViewCountUp.value = true;
  }, 200);
});
</script>

<template>
  <OverviewCardMeshWrap class="ninjadash-overview-card-single">
    <a-card :bordered="false">
      <div :class="`ninjadash-overview-card ninjadash-overview-card-${data?.type}`">
        <div class="ninjadash-overview-card__left d-flex justify-content-between">
          <div :class="`ninjadash-overview-card__left--icon ninjadash-${data?.type}`">
            <unicon :name="data?.icon"></unicon>
          </div>
        </div>
        <div class="ninjadash-overview-card__right">
          <div class="ninjadash-overview-card__right--content">
            <h4 class="ninjadash-overview-total">
              <vue3-autocounter
                ref="counter"
                :startAmount="0"
                :endAmount="didViewCountUp ? Number(data?.total) : 0"
                :duration="2"
                :prefix="data?.prefix"
                :suffix="data?.suffix"
                separator=","
                decimalSeparator="."
                :decimals="data?.decimal"
                :autoinit="true"
              ></vue3-autocounter>
            </h4>
            <span class="ninjadahs-overview-label">{{ data?.label }}</span>
          </div>
          <span :class="`ninjadash-overview-status ninjadash-status-${data?.status}`">
            <span class="ninjadash-status-rate">
              <unicon :name="data?.status === 'growth' ? 'arrow-up' : 'arrow-down'"></unicon>{{ data?.statusRate }}
            </span>
          </span>
        </div>
      </div>
    </a-card>
  </OverviewCardMeshWrap>
</template>

// hexa 8$/hexadash-react/documentation/src/components/cards/OverviewCardMesh.js
/* eslint-disable no-return-assign */
import React, { useState, useEffect } from 'react';
import UilUp from '@iconscout/react-unicons/icons/uil-arrow-up';
import UilDown from '@iconscout/react-unicons/icons/uil-arrow-down';
import propTypes from 'prop-types';
import { Card } from 'antd';
import CountUp from 'react-countup';
import { ReactSVG } from 'react-svg';
import { useLocation } from 'react-router-dom';
import { OverviewCardMeshWrap } from './Style';

const OverviewCardMesh = ({ data }) => {
  const [didViewCountUp, setDidViewCountUp] = useState(false);

  const { pathname } = useLocation();
  useEffect(() => {
    setDidViewCountUp(true);
  }, [pathname]);

  const { type, icon, label, total, status, statusRate, suffix, prefix, decimel } = data;
  const totalNumber = Number(total);
  return (
    <OverviewCardMeshWrap className="ninjadash-overview-card-single">
      <Card bordered={false}>
        <div className={`ninjadash-overview-card ninjadash-overview-card-${type}`}>
          <div className="ninjadash-overview-card__left d-flex justify-content-between">
            <div className={`ninjadash-overview-card__left--icon ninjadash-${type}`}>
              {/* <ReactSVG src={require(`../../static/img/icon/${icon}`)} /> */}
            </div>
          </div>
          <div className="ninjadash-overview-card__right">
            <div className="ninjadash-overview-card__right--content">
              <h4 className="ninjadash-overview-total">
                <CountUp
                  start={0}
                  end={didViewCountUp ? totalNumber : 0}
                  suffix={suffix}
                  prefix={prefix}
                  delay={0.5}
                  decimals={decimel}
                  duration={2}
                />
              </h4>
              <span className="ninjadahs-overview-label">{label}</span>
            </div>
            <span className={`ninjadash-overview-status ninjadash-status-${status}`}>
              <span className="ninjadash-status-rate">
                {status === 'growth' ? <UilUp /> : <UilDown />} {statusRate}%
              </span>
            </span>
          </div>
        </div>
      </Card>
    </OverviewCardMeshWrap>
  );
};
OverviewCardMesh.propTypes = {
  data: {},
};
OverviewCardMesh.propTypes = {
  data: propTypes.object,
};

export default OverviewCardMesh;
