// hexa 8$/hexadash-vue/full-version/src/view/dashboard/overview/demoFour/PerfomanceOverview.vue
<template>
  <BorderLessHeading>
    <sdCards more title="Performance Overview">
      <template #more>
        <router-link to="#">
          <unicon name="print" width="16"></unicon>
          <span>Printer</span>
        </router-link>
        <router-link to="#">
          <unicon name="book-open" width="16"></unicon>
          <span>PDF</span>
        </router-link>
        <router-link to="#">
          <unicon name="file-alt" width="16"></unicon>
          <span>Google Sheets</span>
        </router-link>
        <router-link to="#">
          <unicon name="x" width="16"></unicon>
          <span>Excel (XLSX)</span>
        </router-link>
        <router-link to="#">
          <unicon name="file" width="16"></unicon>
          <span>CSV</span>
        </router-link>
      </template>
      <PerfomanceOverviewStyle>
        <div class="performance-chart-wrap">
          <div class="performance-chart">
            <apexchart
              type="radialBar"
              :options="chartOptions"
              :series="series"
              width="285px"
              height="285px"
            ></apexchart>
          </div>
          <div class="performance-chart-labels">
            <ul>
                <li v-for="(label, index) in labels" :class="`label-${label.replace(/\s+/g, '-').toLowerCase()}`" :key="index">{{ label }}</li>
            </ul>
          </div>
        </div>
      </PerfomanceOverviewStyle>
    </sdCards>
  </BorderLessHeading>
</template>
<script>
import { defineComponent, computed } from "vue";
import { PerfomanceOverviewStyle } from "../../style";
import { BorderLessHeading } from "../../../styled";
import { themeColor } from "@/config/theme/themeVariables";
import { useStore } from "vuex";
import VueApexCharts from "vue3-apexcharts";

export default defineComponent({
  components: {
    PerfomanceOverviewStyle,
    BorderLessHeading,
    apexchart: VueApexCharts
  },
  setup() {
    const { state } = useStore();
    const mainContent = computed(() => state.themeLayout.main);
    const labels = ['Target', 'Completed', 'In Progress'];
    const chartOptions = {
      colors: ['#8231D3', '#00AAFF', '#FA8B0C'],
      chart: {
        sparkline: {
          enabled: true
        }
      },
      legend: {
        show: false
      },
      plotOptions: {
        radialBar: {
          hollow: {
            margin: 0,
            size: '28%'
          },
          track: {
            show: true,
            margin: 11
          },
          dataLabels: {
            show: true,
            name: {
              offsetY: 20
            },
            value: {
              fontSize: '24px',
              fontFamily: '"Jost", sans-serif',
              fontWeight: 600,
              offsetY: -21
            },
            total: {
              show: true,
              label: 'Completed',
              fontSize: '16px',
              fontFamily: '"Jost", sans-serif',
              fontWeight: 400,
              color: `${themeColor[mainContent.value]["gray-color"]}`,
              formatter: function () {
                return '60%';
              }
            }
          }
        }
      },
      stroke: {
        lineCap: 'round'
      },
      grid: {
        padding: {
          to: 0,
          right: 0,
          bottom: 0,
          left: 0
        }
      },
      labels
    };
    const series = [90, 80, 70];

    return {
      mainContent,
      labels,
      chartOptions,
      series
    };
  },
});
</script>

// hexa 8$/hexadash-react/documentation/src/container/dashboard/overview/demoFour/PerfomanceOverview.js
import React from 'react';
import { Link } from 'react-router-dom';
import UilPrint from '@iconscout/react-unicons/icons/uil-print';
import UilBookOpen from '@iconscout/react-unicons/icons/uil-book-open';
import UilFileAlt from '@iconscout/react-unicons/icons/uil-file-alt';
import UilFile from '@iconscout/react-unicons/icons/uil-file';
import UilTimes from '@iconscout/react-unicons/icons/uil-times';
import { Cards } from '../../../../components/cards/frame/cards-frame';
import DoughnutChart from '../../../../components/charts/DoughnutChart';
import { PerfomanceOverviewStyle } from '../../Style';
import { BorderLessHeading, ChartPointHorizontal } from '../../../styled';

const PerformanceOverview = React.memo(() => {

  const moreContent = (
    <>
      <Link to="#">
        <UilPrint />
        <span>Printer</span>
      </Link>
      <Link to="#">
        <UilBookOpen />
        <span>PDF</span>
      </Link>
      <Link to="#">
        <UilFileAlt />
        <span>Google Sheets</span>
      </Link>
      <Link to="#">
        <UilTimes />
        <span>Excel (XLSX)</span>
      </Link>
      <Link to="#">
        <UilFile />
        <span>CSV</span>
      </Link>
    </>
  );
  const labels = ['In Progress', 'Target', 'Completed'];
  
  const options = {
    cutout: 70,
    maintainAspectRatio: false,
    responsive: false,
    borderWidth: 2,
    borderColor: "transparent",
    plugins: {
      legend: {
        display: false,
      },
    },
    tooltips: {},
  };

  const datasets = [
    {
      data: [10, 60, 30],
      backgroundColor: ['#00E4EC', '#FB3586', '#5840FF'],
      centerText: '',
      centerTextLabel: 'Completed',
    },
  ];

  return (
    <BorderLessHeading>
      <Cards more={moreContent} title="Performance Overview" size="large">
        <PerfomanceOverviewStyle>
          <DoughnutChart labels={labels} datasets={datasets} width={180} height={180} option={options} />
          <ChartPointHorizontal>
            <div className="ninjadash-chartpoint">
              {datasets[0].data.map((value, index) => {
                return (
                  <div className="ninjadash-chartpoint__item" key={index}>
                    <span
                      className="ninjadash-chartpoint__tika"
                      style={{
                        backgroundColor: datasets[0].backgroundColor[index],
                      }}
                    />
                    <span className="ninjadash-chartpoint__label">{labels[index]}</span>
                  </div>
                );
              })}
            </div>
          </ChartPointHorizontal>
        </PerfomanceOverviewStyle>
      </Cards>
    </BorderLessHeading>
  );
});

export default PerformanceOverview;
