// hexa 8$/hexadash-react/documentation/src/container/dashboard/overview/demoFour/PerfomanceOverview.js
import React from 'react';
import { Link } from 'react-router-dom';
import UilPrint from '@iconscout/react-unicons/icons/uil-print';
import UilBookOpen from '@iconscout/react-unicons/icons/uil-book-open';
import UilFileAlt from '@iconscout/react-unicons/icons/uil-file-alt';
import UilFile from '@iconscout/react-unicons/icons/uil-file';
import UilTimes from '@iconscout/react-unicons/icons/uil-times';
import { Cards } from '../../../../components/cards/frame/cards-frame';
import DoughnutChart from '../../../../components/charts/DoughnutChart';
import { PerfomanceOverviewStyle } from '../../Style';
import { BorderLessHeading, ChartPointHorizontal } from '../../../styled';

const PerformanceOverview = React.memo(() => {

  const moreContent = (
    <>
      <Link to="#">
        <UilPrint />
        <span>Printer</span>
      </Link>
      <Link to="#">
        <UilBookOpen />
        <span>PDF</span>
      </Link>
      <Link to="#">
        <UilFileAlt />
        <span>Google Sheets</span>
      </Link>
      <Link to="#">
        <UilTimes />
        <span>Excel (XLSX)</span>
      </Link>
      <Link to="#">
        <UilFile />
        <span>CSV</span>
      </Link>
    </>
  );
  const labels = ['In Progress', 'Target', 'Completed'];
  
  const options = {
    cutout: 70,
    maintainAspectRatio: false,
    responsive: false,
    borderWidth: 2,
    borderColor: "transparent",
    plugins: {
      legend: {
        display: false,
      },
    },
    tooltips: {},
  };

  const datasets = [
    {
      data: [10, 60, 30],
      backgroundColor: ['#00E4EC', '#FB3586', '#5840FF'],
      centerText: '',
      centerTextLabel: 'Completed',
    },
  ];

  return (
    <BorderLessHeading>
      <Cards more={moreContent} title="Performance Overview" size="large">
        <PerfomanceOverviewStyle>
          <DoughnutChart labels={labels} datasets={datasets} width={180} height={180} option={options} />
          <ChartPointHorizontal>
            <div className="ninjadash-chartpoint">
              {datasets[0].data.map((value, index) => {
                return (
                  <div className="ninjadash-chartpoint__item" key={index}>
                    <span
                      className="ninjadash-chartpoint__tika"
                      style={{
                        backgroundColor: datasets[0].backgroundColor[index],
                      }}
                    />
                    <span className="ninjadash-chartpoint__label">{labels[index]}</span>
                  </div>
                );
              })}
            </div>
          </ChartPointHorizontal>
        </PerfomanceOverviewStyle>
      </Cards>
    </BorderLessHeading>
  );
});

export default PerformanceOverview;

// hexa 8$/hexadash-vue/full-version/src/view/dashboard/overview/demoNine/PerfomanceOverview.vue
<template>
  <BorderLessHeading>
    <sdCards more title="Performance Overview">
      <template #more>
        <router-link to="#">
          <unicon name="print" width="16"></unicon>
          <span>Printer</span>
        </router-link>
        <router-link to="#">
          <unicon name="book-open" width="16"></unicon>
          <span>PDF</span>
        </router-link>
        <router-link to="#">
          <unicon name="file-alt" width="16"></unicon>
          <span>Google Sheets</span>
        </router-link>
        <router-link to="#">
          <unicon name="x" width="16"></unicon>
          <span>Excel (XLSX)</span>
        </router-link>
        <router-link to="#">
          <unicon name="file" width="16"></unicon>
          <span>CSV</span>
        </router-link>
      </template>
      <PerfomanceOverviewStyle>
        <DoughnutChart
          :labels="labels"
          :datasets="datasets"
          :width="180"
          :height="180"
          :options="options"
          className="ninjadash-chartpoint-graph"
          id="ninjadash-chartpoint-graph"
        />
        <ChartPointHorizontal>
          <div class="ninjadash-chartpoint">
            <div
              v-for="(value, index) in datasets[0].data"
              class="ninjadash-chartpoint__item"
              :key="index"
            >
              <span
                class="ninjadash-chartpoint__tika"
                :style="{
                  backgroundColor: datasets[0].backgroundColor[index],
                }"
              />
              <span class="ninjadash-chartpoint__label">{{
                labels[index]
              }}</span>
            </div>
          </div>
        </ChartPointHorizontal>
      </PerfomanceOverviewStyle>
    </sdCards>
  </BorderLessHeading>
</template>
<script>
import { defineComponent, computed } from "vue";
import DoughnutChart from "@/components/utilities/DoughnutChart.vue";
import { PerfomanceOverviewStyle } from "../../style";
import { BorderLessHeading, ChartPointHorizontal } from "../../../styled";
import { themeColor } from "@/config/theme/themeVariables";
import { useStore } from "vuex";

const labels = ["Todo", "Completed", "In Progress"];

const datasets = [
  {
    data: [40, 15, 5],
    backgroundColor: ["#8231D3", "#5840FF", "#00E4EC"],
    centerText: "15%",
    centerTextLabel: "Completed",
  },
];

export default defineComponent({
  components: {
    DoughnutChart,
    PerfomanceOverviewStyle,
    BorderLessHeading,
    ChartPointHorizontal,
  },
  setup() {
    const { state } = useStore();
    const mainContent = computed(() => state.themeLayout.main);
    const options = {
      cutout: 70,
      maintainAspectRatio: false,
      responsive: false,
      borderWidth: 2,
      borderColor: `${themeColor[mainContent.value]["white-background"]}`,
      plugins: {
        legend: {
          display: false,
        },
      },
    };
    return {
      datasets,
      labels,
      options,
    };
  },
});
</script>
