// hexa 8$/hexadash-react/documentation/src/components/popup/popup.js
import React from 'react';
import PropTypes from 'prop-types';
import './style.css';
import { Link } from 'react-router-dom';
import UilCheck from '@iconscout/react-unicons/icons/uil-check';
import { Content, PopoverStyle, Title } from './style';

const Popover =(props) => {
  const { content, placement, title, action, children } = props;
  const content1 = <Content>{content}</Content>;

  return (
    <PopoverStyle placement={placement} title={title && <Title>{title}</Title>} content={content1} trigger={action}>
      {children}
    </PopoverStyle>
  );
};

const content = (
  <>
    <Link to="#">
      <UilCheck />
      <span>Btn Dropdown one</span>
    </Link>
    <Link to="#">
      <UilCheck />
      <span>Btn Dropdown two</span>
    </Link>
    <Link to="#">
      <UilCheck />
      <span>Btn Dropdown three</span>
    </Link>
  </>
);

Popover.defaultProps = {
  action: 'hover',
  placement: 'bottom',
  content,
};

Popover.propTypes = {
  placement: PropTypes.string,
  title: PropTypes.string,
  action: PropTypes.string,
  content: PropTypes.node,
  children: PropTypes.node.isRequired,
};

export { Popover };

// hexa 8$/hexadash-typescript-vue/full-version/src/components/popup/Popup.vue
<script lang="ts">
import { Contents, TitleStyle } from './style';
import { defineComponent, ref, reactive } from 'vue';

export default defineComponent({
  name: 'Popover',
  components: {
    Contents,
    TitleStyle,
  },
  props: {
    placement: {
      type: String,
      default: 'bottom',
    },
    title: {
      type: String,
      default: '',
    },
    class: {
      type: String,
      default: '',
    },
    action: {
      type: String,
      default: 'hover',
    },
  },
  setup() {
    const visible = ref(false);
    const className = reactive({ value: '' });
    const classRef = (value: any) => {
      className.value = value;
    };
    return {
      visible,
      className,
      classRef,
    };
  },
});
</script>

<template>
  <a-popover :class="className" v-model="visible" :placement="placement" :title="title && title" :trigger="action">
    <template v-if="title" v-slot:title>
      <TitleStyle>{{ title }}</TitleStyle>
    </template>
    <template v-slot:content>
      <Contents>
        <slot name="content">
          <a to="#">
            <unicon name="check" width="16"></unicon>
            <span>Btn Dropdown one</span>
          </a>
          <a to="#">
            <unicon name="check" width="16"></unicon>
            <span>Btn Dropdown two</span>
          </a>
          <a to="#">
            <unicon name="check" width="16"></unicon>
            <span>Btn Dropdown three</span>
          </a>
        </slot>
      </Contents>
    </template>
    <slot></slot>
  </a-popover>
</template>

<style>
@import './style.css';
</style>
