// hexa 8$/hexadash-react/documentation/src/container/pages/overview/info.js
import React, { useState } from 'react';
import { Row, Col, Form, Input, Upload, Select } from 'antd';
import { Link } from 'react-router-dom';
import UilCamera from '@iconscout/react-unicons/icons/uil-camera';
import { BasicFormWrapper } from '../../styled';
import { Button } from '../../../components/buttons/buttons';
import Heading from '../../../components/heading/heading';

const { Option } = Select;
const Info = () => {
  const [state, setState] = useState({
    values: '',
  });
  const [form] = Form.useForm();
  const handleSubmit = values => {
    setState({ ...state, values });
  };

  return (
    <Row justify="center">
      <Col xxl={10} xl={14} md={16} xs={24}>
        <div className="user-info-form">
          <BasicFormWrapper>
            <Form style={{ width: '100%' }} form={form} name="info" onFinish={handleSubmit}>
              <Heading className="form-title" as="h4">
                Personal Information
              </Heading>

              <figure className="photo-upload align-center-v">
                <img src={require('../../../static/img/avatar/profileImage.png')} alt="" />
                <figcaption>
                  <Upload>
                    <Link className="btn-upload" to="#">
                      <UilCamera />
                    </Link>
                  </Upload>
                  <div className="info">
                    <Heading as="h4">Profile Photo</Heading>
                  </div>
                </figcaption>
              </figure>

              <Form.Item label="Name" name="name">
                <Input placeholder="Input Name" />
              </Form.Item>

              <Form.Item
                label="Email Address"
                name="email"
                rules={[{ message: 'Please input your email!', type: 'email' }]}
              >
                <Input placeholder="name@example.com" />
              </Form.Item>

              <Form.Item name="phone" label="Phone Number">
                <Input placeholder="+440 2546 5236" />
              </Form.Item>

              <Form.Item name="country" initialValue="" label="Country">
                <Select style={{ width: '100%' }}>
                  <Option value="">Please Select</Option>
                  <Option value="bangladesh">Bangladesh</Option>
                  <Option value="india">India</Option>
                  <Option value="pakistan">Pakistan</Option>
                </Select>
              </Form.Item>

              <Form.Item initialValue="" name="city" label="City">
                <Select style={{ width: '100%' }}>
                  <Option value="">Please Select</Option>
                  <Option value="dhaka">Dhaka</Option>
                  <Option value="khulna">Khulna</Option>
                  <Option value="barisal">Barisal</Option>
                </Select>
              </Form.Item>

              <Form.Item name="website" label="Website">
                <Input placeholder="www.example.com" />
              </Form.Item>

              <Form.Item>
                <div className="add-user-bottom text-right">
                  <Button
                    className="ant-btn ant-btn-light"
                    onClick={() => {
                      return form.resetFields();
                    }}
                  >
                    Reset
                  </Button>
                  <Button htmlType="submit" type="primary">
                    <Link to="/admin/users/add-user/work">Save & Next</Link>
                  </Button>
                </div>
              </Form.Item>
            </Form>
          </BasicFormWrapper>
        </div>
      </Col>
    </Row>
  );
};

export default Info;

// hexa 8$/hexadash-vue/full-version/src/view/apps/users/overview/Info.vue
<template>
  <a-row justify="center">
    <a-col :xl="10" :md="16" :xs="24">
      <div class="user-info-form">
        <BasicFormWrapper>
          <a-form
            style="width: 100%"
            name="info"
            :model="formState"
            :rules="rules"
            @finish="handleFinish"
            @finishFailed="handleFinishFailed"
            :layout="formState.layout"
          >
            <sdHeading class="form-title" as="h4">
              Personal Information
            </sdHeading>

            <figure class="photo-upload align-center-v">
              <img
                :src="require('@/static/img/avatar/profileImage.png')"
                alt=""
              />
              <figcaption>
                <a-upload>
                  <a class="btn-upload" to="#">
                    <unicon name="camera" width="16"></unicon>
                  </a>
                </a-upload>
                <div class="info">
                  <sdHeading as="h4">Profile Photo</sdHeading>
                </div>
              </figcaption>
            </figure>

            <a-form-item label="Name" name="name">
              <a-input
                v-model:value="formState.name"
                placeholder="Input Name"
              />
            </a-form-item>

            <a-form-item label="Email Address" name="email">
              <a-input
                v-model:value="formState.email"
                placeholder="name@example.com"
              />
            </a-form-item>

            <a-form-item name="phone" label="Phone Number">
              <a-input
                v-model:value="formState.phone"
                placeholder="+440 2546 5236"
              />
            </a-form-item>

            <a-form-item name="country" label="Country">
              <a-select v-model:value="formState.country" style="width: 100%">
                <a-select-option value="">Please Select</a-select-option>
                <a-select-option value="bangladesh">Bangladesh</a-select-option>
                <a-select-option value="india">India</a-select-option>
                <a-select-option value="pakistan">Pakistan</a-select-option>
              </a-select>
            </a-form-item>

            <a-form-item name="city" label="City">
              <a-select v-model:value="formState.city" style="width: 100%">
                <a-select-option value="">Please Select</a-select-option>
                <a-select-option value="dhaka">Dhaka</a-select-option>
                <a-select-option value="khulna">Khulna</a-select-option>
                <a-select-option value="barisal">Barisal</a-select-option>
              </a-select>
            </a-form-item>

            <a-form-item name="website" label="Website">
              <a-input
                v-model:value="formState.website"
                placeholder="www.example.com"
              />
            </a-form-item>

            <a-form-item>
              <div class="add-user-bottom text-right">
                <sdButton class="ant-btn ant-btn-light"> Reset </sdButton>
                <sdButton htmlType="submit" type="primary">
                  <router-link to="work">Save & Next</router-link>
                </sdButton>
              </div>
            </a-form-item>
          </a-form>
        </BasicFormWrapper>
      </div>
    </a-col>
  </a-row>
</template>
<script>
import { BasicFormWrapper } from "../../../styled";
import { reactive, ref, defineComponent } from "vue";
const Info = defineComponent({
  name: "Info",
  components: { BasicFormWrapper },
  setup() {
    const values = ref("");
    const formState = reactive({
      name: "",
      email: "",
      phone: "",
      country: "",
      city: "",
      website: "",
      layout: "vertical",
    });

    const rules = {
      name: [
        {
          required: true,
          message: "Please input Activity name",
          trigger: "blur",
        },
      ],
      email: [
        {
          required: true,
          message: "Please input Activity email",
          trigger: "blur",
        },
        {
          type: "email",
          message: "Please input a valid email",
          trigger: "blur",
        },
      ],
    };

    const handleFinish = (values) => {
      values.value = values;
    };

    const handleFinishFailed = (errors) => {
      console.log(errors);
    };
    return {
      values,
      formState,
      handleFinish,
      handleFinishFailed,
      rules,
    };
  },
});

export default Info;
</script>
