// hexa 8$/hexadash-react/documentation/src/container/dashboard/DashboardBase.js
import React from 'react';
import { Row, Col } from 'antd';
import { PageHeader } from '../../components/page-headers/page-headers';
import { Cards } from '../../components/cards/frame/cards-frame';
import { Button } from '../../components/buttons/buttons';
import { Main } from '../styled';
import { DashboardBaseStyleWrap } from './Style';
import Palette from '../../components/color-palette/palette';
import config from '../../config/config';
import Heading from '../../components/heading/heading';

// @Todo console warning from button

const { themeColor } = config;
const DashboardBase = () => {
  const PageRoutes = [
    {
      path: '/admin',
      breadcrumbName: 'Dashboard',
    },
    {
      path: '',
      breadcrumbName: 'Theme Configuration',
    },
  ];
  return (
    <>
      <PageHeader className="ninjadash-page-header-main" title="Theme Configuration" routes={PageRoutes} />
      <Main>
        <Row gutter={15}>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless title="Theme Colors" size="large">
                <div className="ninjadash-configuration-box align-center-v">
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="primary">
                      Primary
                    </Button>
                    <span className="ninjadah-color-code">#FB3586</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="secondary">
                      Secondary
                    </Button>
                    <span className="ninjadah-color-code">#5840FF</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="success">
                      Success
                    </Button>
                    <span className="ninjadah-color-code">#01B81A</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="info">
                      Info
                    </Button>
                    <span className="ninjadah-color-code">#00AAFF</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="warning">
                      Warning
                    </Button>
                    <span className="ninjadah-color-code">#FA8B0C</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="danger">
                      Danger
                    </Button>
                    <span className="ninjadah-color-code">#FF0F0F</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="dark">
                      Dark
                    </Button>
                    <span className="ninjadah-color-code">#090E30</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="gray">
                      Gray
                    </Button>
                    <span className="ninjadah-color-code">#525768</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="light">
                      Light
                    </Button>
                    <span className="ninjadah-color-code">#8C90A4</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="extra-light">
                      Extra Light
                    </Button>
                    <span className="ninjadah-color-code">#ADB5D9</span>
                  </div>
                </div>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless title="Hover Colors" size="large">
              <div className="ninjadash-configuration-box ninjadash-configuration-box-button-hover align-center-v">
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="primary">
                      Primary
                    </Button>
                    <span className="ninjadah-color-code">#4347D9</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="secondary">
                      Secondary
                    </Button>
                    <span className="ninjadah-color-code">#E34A87</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="success">
                      Success
                    </Button>
                    <span className="ninjadah-color-code">#0CAB7C</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="info">
                      Info
                    </Button>
                    <span className="ninjadah-color-code">#0D79DF</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="warning">
                      Warning
                    </Button>
                    <span className="ninjadah-color-code">#D47407</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="danger">
                      Danger
                    </Button>
                    <span className="ninjadah-color-code">#E30D0F</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="dark">
                      Dark
                    </Button>
                    <span className="ninjadah-color-code">#131623</span>
                  </div>
                  <div className="ninjadash-configuration-box__item">
                    <Button size="default" type="gray">
                      Gray
                    </Button>
                    <span className="ninjadah-color-code">#363A51</span>
                  </div>
                </div>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless title="Gradient Colors" size="large">
                <Row gutter={15}>
                  <Col md={5}>
                    <Palette
                      gradient
                      content
                      direction="90deg"
                      colorCode={[themeColor['secondary-color'], "#00E4EC"]}
                    >
                      {themeColor['secondary-color']}
                    </Palette>
                  </Col>
                </Row>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless title="Border Colors" size="large">
                <Row gutter={15}>
                  <Col md={6}>
                    <Palette bordered content colorCode={themeColor['border-color-light']}>
                      Border Color 1
                    </Palette>
                  </Col>
                  <Col md={6}>
                    <Palette bordered content colorCode={themeColor['border-color-normal']}>
                      Border Color 2
                    </Palette>
                  </Col>
                  <Col md={6}>
                    <Palette bordered content colorCode={themeColor['border-color-deep']}>
                      Border Color 3
                    </Palette>
                  </Col>
                </Row>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless title="Background Gray Colors" size="large">
                <Row gutter={15}>
                  <Col md={6}>
                    <Palette bg content colorCode={themeColor['bg-color-light']}>
                      BG Color 1
                    </Palette>
                  </Col>
                  <Col md={6}>
                    <Palette bg content colorCode={themeColor['bg-color-normal']}>
                      BG Color 2
                    </Palette>
                  </Col>
                  <Col md={6}>
                    <Palette bg content colorCode={themeColor['bg-color-deep']}>
                      BG Color 3
                    </Palette>
                  </Col>
                </Row>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless title="Buttons" size="large">
                <Row gutter={15}>
                  <Col md={8}>
                    <Button type="primary" size="extra-small" style={{ marginRight: '10px', marginBottom: '30px' }} raised>
                      Extra Small
                    </Button>
                    <Button type="primary" size="small" style={{ marginRight: '10px', marginBottom: '30px' }} raised>
                      Small
                    </Button>
                    <Button type="primary" size="default" style={{ marginRight: '10px', marginBottom: '30px' }} raised>
                      Normal
                    </Button>
                    <Button type="primary" size="large" style={{ marginRight: '10px', marginBottom: '30px' }} raised>
                      Large Button
                    </Button>
                    <Button outlined type="primary" size="extra-small" style={{ marginRight: '10px', marginBottom: '30px' }}>
                      Extra Small
                    </Button>
                    <Button outlined type="primary" size="small" style={{ marginRight: '10px', marginBottom: '30px' }}>
                      Small
                    </Button>
                    <Button outlined type="primary" size="default" style={{ marginRight: '10px', marginBottom: '30px' }}>
                      Normal
                    </Button>
                    <Button outlined type="primary" size="large" style={{ marginRight: '10px', marginBottom: '30px' }} transparented>
                      Large Button
                    </Button>
                    <Button type="primary" size="extra-small" style={{ marginRight: '10px', marginBottom: '30px' }} transparented>
                      Extra Small
                    </Button>
                    <Button type="primary" size="small" style={{ marginRight: '10px', marginBottom: '30px' }} transparented>
                      Small
                    </Button>
                    <Button type="primary" size="default" style={{ marginRight: '10px', marginBottom: '30px' }} transparented>
                      Normal
                    </Button>
                    <Button type="primary" size="large" transparented>
                      Large Button
                    </Button>
                  </Col>
                </Row>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless title={<span>Typography <span className="color-primary">Jost</span></span>} size="large">
                <div className="ninjadash-heading-typography">
                  <Row gutter={15}>
                    <Col xs={24}>
                      <Row align="middle">
                        <Col lg={9} sm={24} xs={24}>
                          <Heading>h1. Default Heading</Heading>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-primary">Font Size - 30px</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-secondary">Font weight - 600</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-info">Line Height - 38px</p>
                        </Col>
                      </Row>
                    </Col>
                    <Col xs={24}>
                      <Row align="middle">
                        <Col lg={9} sm={24} xs={24}>
                          <Heading as="h2">h2. Default Heading</Heading>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-primary">Font Size - 24px</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-secondary">Font weight - 600</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-info">Line Height - 30px</p>
                        </Col>
                      </Row>
                    </Col>
                    <Col xs={24}>
                      <Row align="middle">
                        <Col lg={9} sm={24} xs={24}>
                          <Heading as="h3">h3. Default Heading</Heading>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-primary">Font Size - 22px</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-secondary">Font weight - 600</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-info">Line Height - 27px</p>
                        </Col>
                      </Row>
                    </Col>
                    <Col xs={24}>
                      <Row align="middle">
                        <Col lg={9} sm={24} xs={24}>
                          <Heading as="h4">h4. Default Heading</Heading>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-primary">Font Size - 20px</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-secondary">Font weight - 600</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-info">Line Height - 24px</p>
                        </Col>
                      </Row>
                    </Col>
                    <Col xs={24}>
                      <Row align="middle">
                        <Col lg={9} sm={24} xs={24}>
                          <Heading as="h5">h5. Default Heading</Heading>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-primary">Font Size - 18px</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-secondary">Font weight - 600</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-info">Line Height - 22px</p>
                        </Col>
                      </Row>
                    </Col>
                    <Col xs={24}>
                      <Row align="middle">
                        <Col lg={9} sm={24} xs={24}>
                          <Heading as="h6">h6. Default Heading</Heading>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-primary">Font Size - 16px</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-secondary">Font weight - 600</p>
                        </Col>
                        <Col lg={5} sm={24} xs={24}>
                          <p className="color-info">Line Height - 20px</p>
                        </Col>
                      </Row>
                    </Col>
                  </Row>
                </div>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
          <Col xs={24}>
            <DashboardBaseStyleWrap>
              <Cards headless size="large">
                <div className="ninjadash-body-typography">
                  <div className="ninjadash-body-typography__top">
                    <Heading as="h5">Body Text Normal</Heading>
                    <ul className="ninjadash-typo-list">
                      <li>Font Size - 15px</li>
                      <li>Font weight - 400</li>
                      <li>Line height - 25px</li>
                    </ul>
                  </div>
                  <div className="ninjadash-body-typography__text">
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
                  </div>
                </div>
                <div className="ninjadash-body-typography typo-small">
                  <div className="ninjadash-body-typography__top">
                    <Heading as="h5">Body Text Small</Heading>
                    <ul className="ninjadash-typo-list">
                      <li>Font Size - 14px</li>
                      <li>Font weight - 400</li>
                      <li>Line height - 22px</li>
                    </ul>
                  </div>
                  <div className="ninjadash-body-typography__text">
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
                  </div>
                </div>
                <div className="ninjadash-body-typography typo-big">
                  <div className="ninjadash-body-typography__top">
                    <Heading as="h5">Body Text Big</Heading>
                    <ul className="ninjadash-typo-list">
                      <li>Font Size - 16px</li>
                      <li>Font weight - 400</li>
                      <li>Line height - 27px</li>
                    </ul>
                  </div>
                  <div className="ninjadash-body-typography__text">
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod</p>
                  </div>
                </div>
              </Cards>
            </DashboardBaseStyleWrap>
          </Col>
        </Row>
      </Main>
    </>
  );
};

export default DashboardBase;

// hexa 8$/hexadash-vue/full-version/src/view/uiElements/DashboardBase.vue
<template>
  <div>
    <sdPageHeader
      class="ninjadash-page-header-main"
      title="Theme Configuration"
    >
    </sdPageHeader>
    <Main>
      <a-row :gutter="25">
        <a-col :xs="24">
          <DashboardBaseStyleWrap>
            <sdCards
              :border="false"
              headless
              title="Theme Colors"
              size="default"
            >
              <a-row :gutter="15">
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['primary-color']">Primary</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['secondary-color']"
                    >Secondary</Palette
                  >
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['success-color']">Success</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['info-color']">Info</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['warning-color']">Warning</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['error-color']">Error</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['dark-color']">Dark</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['gray-color']">Gray</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['light-color']">Light</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['extra-light-color']"
                    >Extra Light</Palette
                  >
                </a-col>
              </a-row>
            </sdCards>
          </DashboardBaseStyleWrap>
        </a-col>
        <a-col :xs="24">
          <DashboardBaseStyleWrap>
            <sdCards
              :border="false"
              headless
              title="Hover Colors"
              size="default"
            >
              <a-row :gutter="15">
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['primary-hover']">Primary</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['secondary-hover']"
                    >Secondary</Palette
                  >
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['success-hover']">Success</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['info-hover']">Info</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['warning-hover']">Warning</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['error-hover']">Error</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['dark-hover']">Dark</Palette>
                </a-col>
                <a-col :xxl="2" :xl="3" :lg="4" :md="6" :sm="8" :xs="12">
                  <Palette :colorCode="theme['gray-hover']">Gray</Palette>
                </a-col>
              </a-row>
            </sdCards>
          </DashboardBaseStyleWrap>
        </a-col>
        <a-col :xs="24">
          <DashboardBaseStyleWrap>
            <sdCards
              :border="false"
              headless
              title="Gradient Colors"
              size="default"
            >
              <a-row :gutter="15">
                <a-col :md="5">
                  <Palette
                    gradient
                    content
                    direction="90deg"
                    :colorCode="[
                      theme['primary-color'],
                      theme['secondary-color'],
                    ]"
                  >
                    {{ theme["primary-color"] }}
                  </Palette>
                </a-col>
                <a-col :md="5">
                  <Palette
                    gradient
                    content
                    direction="90deg"
                    :colorCode="[
                      theme['secondary-color'],
                      theme['warning-color'],
                    ]"
                  >
                    {{ theme["secondary-color"] }}
                  </Palette>
                </a-col>
                <a-col :md="5">
                  <Palette
                    gradient
                    content
                    direction="90deg"
                    :colorCode="[theme['primary-color'], theme['info-color']]"
                  >
                    {{ theme["primary-color"] }}
                  </Palette>
                </a-col>
              </a-row>
            </sdCards>
          </DashboardBaseStyleWrap>
        </a-col>
        <a-col :xs="24">
          <DashboardBaseStyleWrap>
            <sdCards
              :border="false"
              headless
              title="Border Colors"
              size="default"
            >
              <a-row :gutter="15">
                <a-col :md="6">
                  <Palette
                    :bordered="true"
                    :content="true"
                    :colorCode="theme['border-color-light']"
                  >
                    Border Color 1
                  </Palette>
                </a-col>
                <a-col :md="6">
                  <Palette
                    :bordered="true"
                    :content="true"
                    :colorCode="theme['border-color-normal']"
                  >
                    Border Color 2
                  </Palette>
                </a-col>
                <a-col :md="6">
                  <Palette
                    :bordered="true"
                    :content="true"
                    :colorCode="theme['border-color-deep']"
                  >
                    Border Color 3
                  </Palette>
                </a-col>
              </a-row>
            </sdCards>
          </DashboardBaseStyleWrap>
        </a-col>
        <a-col :xs="24">
          <DashboardBaseStyleWrap>
            <sdCards
              :border="false"
              headless
              title="Background Gray Colors"
              size="default"
            >
              <a-row :gutter="15">
                <a-col :md="6">
                  <Palette bg content :colorCode="theme['bg-color-light']">
                    BG Color 1
                  </Palette>
                </a-col>
                <a-col :md="6">
                  <Palette bg content :colorCode="theme['bg-color-normal']">
                    BG Color 2
                  </Palette>
                </a-col>
                <a-col :md="6">
                  <Palette bg content :colorCode="theme['bg-color-deep']">
                    BG Color 3
                  </Palette>
                </a-col>
              </a-row>
            </sdCards>
          </DashboardBaseStyleWrap>
        </a-col>
        <a-col :xs="24">
          <DashboardBaseStyleWrap>
            <sdCards headless title="Buttons">
              <a-row :gutter="15">
                <a-col :md="6">
                  <sdButton
                    type="primary"
                    size="sm"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Small
                  </sdButton>
                  <sdButton
                    type="primary"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Normal
                  </sdButton>
                  <sdButton
                    type="primary"
                    size="lg"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Large Button
                  </sdButton>
                  <sdButton
                    outlined
                    type="primary"
                    size="sm"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Small
                  </sdButton>
                  <sdButton
                    outlined
                    type="primary"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Normal
                  </sdButton>
                  <sdButton
                    outlined
                    type="primary"
                    size="lg"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Large Button
                  </sdButton>
                  <sdButton
                    type="secondary"
                    size="sm"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Small
                  </sdButton>
                  <sdButton
                    type="secondary"
                    :style="{ marginRight: '10px', marginBottom: '10px' }"
                  >
                    Normal
                  </sdButton>
                  <sdButton
                    type="secondary"
                    size="lg"
                    :style="{ [rtl ? 'marginRight' : '']: '10px' }"
                  >
                    Large Button
                  </sdButton>
                </a-col>
              </a-row>
            </sdCards>
          </DashboardBaseStyleWrap>
        </a-col>
        <a-col :xs="24">
          <DashboardBaseStyleWrap>
            <sdCards headless title="Typography Inter">
              <a-row :gutter="15">
                <a-col :xs="24">
                  <a-row>
                    <a-col :lg="9" :sm="24" :xs="24">
                      <sdHeading>h1. Default Heading</sdHeading>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font Size - 30px</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font weight - 600</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Line Height - 38px</p>
                    </a-col>
                  </a-row>
                </a-col>
                <a-col :xs="24">
                  <a-row>
                    <a-col :lg="9" :sm="24" :xs="24">
                      <sdHeading as="h2">h2. Default Heading</sdHeading>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font Size - 24px</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font weight - 600</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Line Height - 30px</p>
                    </a-col>
                  </a-row>
                </a-col>
                <a-col :xs="24">
                  <a-row>
                    <a-col :lg="9" :sm="24" :xs="24">
                      <sdHeading as="h3">h3. Default Heading</sdHeading>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font Size - 22px</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font weight - 600</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Line Height - 27px</p>
                    </a-col>
                  </a-row>
                </a-col>
                <a-col :xs="24">
                  <a-row>
                    <a-col :lg="9" :sm="24" :xs="24">
                      <sdHeading as="h4">h4. Default Heading</sdHeading>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font Size - 20px</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font weight - 600</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Line Height - 24px</p>
                    </a-col>
                  </a-row>
                </a-col>
                <a-col :xs="24">
                  <a-row>
                    <a-col :lg="9" :sm="24" :xs="24">
                      <sdHeading as="h5">h5. Default Heading</sdHeading>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font Size - 18px</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font weight - 600</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Line Height - 22px</p>
                    </a-col>
                  </a-row>
                </a-col>
                <a-col :xs="24">
                  <a-row>
                    <a-col :lg="9" :sm="24" :xs="24">
                      <sdHeading as="h6">h6. Default Heading</sdHeading>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font Size - 16px</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Font weight - 600</p>
                    </a-col>
                    <a-col :lg="5" :sm="24" :xs="24">
                      <p>Line Height - 20px</p>
                    </a-col>
                  </a-row>
                </a-col>
              </a-row>
            </sdCards>
          </DashboardBaseStyleWrap>
        </a-col>
      </a-row>
    </Main>
  </div>
</template>

<script>
import { Main } from "../styled";
import { DashboardBaseStyleWrap } from "./ui-elements-styled";
import Palette from "../../components/color-palette/palette";
import { theme } from "../../config/theme/themeVariables";
import { computed, defineComponent } from "vue";
import { useStore } from "vuex";
export default defineComponent({
  name: "ThemeConfiguration",
  components: {
    Main,
    DashboardBaseStyleWrap,
    Palette,
  },
  setup() {
    const { state } = useStore();
    const rtl = computed(() => state.themeLayout.rtlData);

    return {
      rtl,
    };
  },
  data() {
    return {
      theme,
    };
  },
  methods: {},
});
</script>
