// hexa 8$/hexadash-vue/full-version/src/view/apps/users/overview/TeamCard.vue
<template>
  <sdUserCard>
    <div class="card team-card">
      <sdCards headless>
        <figure>
          <img :src="require(`@/${user.img}`)" alt="" />
          <figcaption>
            <div class="edit">
              <sdDropdown :action="['click']" class="wide-dropdwon">
                <template #overlay>
                  <slot name="item"></slot>
                </template>
                <a class="card__more_actions" to="#">
                  <unicon name="ellipsis-h" width="16"></unicon>
                </a>
              </sdDropdown>
            </div>
            <sdHeading class="card__name" as="h6">
              <a to="#">{{ user.name }}</a>
            </sdHeading>
            <span class="card__designation">{{ user.designation }}</span>
            <div class="card__social">
              <a class="btn-icon facebook" to="#">
                <font-awesome-icon
                  class="super-crazy-colors"
                  :icon="faFacebookF"
                  size="1x"
                  :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
                />
              </a>
              <a class="btn-icon twitter" to="#">
                <font-awesome-icon
                  class="super-crazy-colors"
                  :icon="faTwitter"
                  size="1x"
                  :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
                />
              </a>
              <a class="btn-icon dribble" to="#">
                <font-awesome-icon
                  class="super-crazy-colors"
                  :icon="faDribbble"
                  size="1x"
                  :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
                />
              </a>
              <a class="btn-icon instagram" to="#">
                <font-awesome-icon
                  class="super-crazy-colors"
                  :icon="faInstagram"
                  size="1x"
                  :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
                />
              </a>
            </div>
          </figcaption>
        </figure>
      </sdCards>
    </div>
  </sdUserCard>
</template>
<script>
import PropTypes from "vue-types";
import { defineComponent } from "vue";
import {
  faFacebookF,
  faDribbble,
  faTwitter,
  faInstagram,
  faGithub,
  faMediumM,
} from "@fortawesome/free-brands-svg-icons";

const TeamCard = defineComponent({
  name: "TeamCard",
  props: {
    user: PropTypes.object,
    actions: PropTypes.node,
  },
  setup() {
    return {
      faFacebookF,
      faDribbble,
      faTwitter,
      faInstagram,
      faGithub,
      faMediumM,
    };
  },
});

export default TeamCard;
</script>

// hexa 8$/hexadash-react/documentation/src/container/pages/overview/TeamCard.js
import React from 'react';
import UilEllipsisH from '@iconscout/react-unicons/icons/uil-ellipsis-h';
import { Link } from 'react-router-dom';
import FontAwesome from 'react-fontawesome';
import PropTypes from 'prop-types';
import { UserCard } from '../style';
import Heading from '../../../components/heading/heading';
import { Cards } from '../../../components/cards/frame/cards-frame';
import { Dropdown } from '../../../components/dropdown/dropdown';

const TeamCard = ({ user, actions }) => {
  const { name, designation, img } = user;

  return (
    <UserCard>
      <div className="card team-card">
        <Cards headless>
          <figure>
            <img src={require(`../../../${img}`)} alt="" />
            <figcaption>
              <div className="edit">
                <Dropdown content={actions} action={['click']} className="wide-dropdwon">
                  <Link className="card__more_actions" to="#">
                    <UilEllipsisH />
                  </Link>
                </Dropdown>
              </div>
              <Heading className="card__name" as="h6">
                <Link to="#">{name}</Link>
              </Heading>
              <span className="card__designation">{designation}</span>
              <div className="card__social">
                <Link className="btn-icon facebook" to="#">
                  <FontAwesome name="facebook" />
                </Link>
                <Link className="btn-icon twitter" to="#">
                  <FontAwesome name="twitter" />
                </Link>
                <Link className="btn-icon dribble" to="#">
                  <FontAwesome name="dribbble" />
                </Link>
                <Link className="btn-icon instagram" to="#">
                  <FontAwesome name="instagram" />
                </Link>
              </div>
            </figcaption>
          </figure>
        </Cards>
      </div>
    </UserCard>
  );
};

TeamCard.propTypes = {
  user: PropTypes.object,
  actions: PropTypes.node,
};

export default TeamCard;
