// hexa 8$/hexadash-vue/full-version/src/view/apps/users/overview/UserCardList.vue
<template>
  <a-col
    v-for="{ name, designation, img, content, id } in users"
    :key="id"
    :xxl="12"
    :xl="12"
    :sm="24"
    :xs="24"
  >
    <sdUserCard>
      <div class="card user-card theme-list">
        <sdCards headless>
          <figure>
            <img :src="require(`@/${img}`)" alt="" />

            <figcaption>
              <div class="card__content">
                <sdHeading class="card__name" as="h6">
                  <a to="#">{{ name }}</a>
                </sdHeading>
                <p class="card__designation">{{ designation }}</p>
                <p class="card-text">{{ content }}</p>
                <p class="card-info">
                  <span class="user-meta"> <strong>$25/</strong>hr </span>
                  <span class="user-meta"> <strong>$88K</strong> earned </span>
                </p>
              </div>

              <div class="card__actions">
                <sdButton size="default" outlined type="white">
                  View Profile
                </sdButton>
                <sdButton size="default" outlined type="white">
                  Message
                </sdButton>
              </div>
            </figcaption>
          </figure>
        </sdCards>
      </div>
    </sdUserCard>
  </a-col>
</template>
<script>
import users from "@/demoData/usersData.json";
import { defineComponent } from "vue";
const UserCardList = defineComponent({
  name: "UserCardList",
  setup() {
    return {
      users,
    };
  },
});

export default UserCardList;
</script>

// hexa 8$/hexadash-react/documentation/src/container/pages/overview/UserCardList.js
import React from 'react';
import { Link } from 'react-router-dom';
import PropTypes from 'prop-types';
import { UserCard } from '../style';
import Heading from '../../../components/heading/heading';
import { Cards } from '../../../components/cards/frame/cards-frame';
import { Button } from '../../../components/buttons/buttons';

const UserCardList = ({ user }) => {
  const { name, designation, img, content } = user;
  return (
    <UserCard>
      <div className="card user-card theme-list">
        <Cards headless>
          <figure>
            <img src={require(`../../../${img}`)} alt="" />

            <figcaption>
              <div className="card__content">
                <Heading className="card__name" as="h6">
                  <Link to="#">{name}</Link>
                </Heading>
                <p className="card__designation">{designation}</p>
                <p className="card-text">{content}</p>
                <p className="card-info">
                  <span className="user-meta">
                    <strong>$25/</strong>hr
                  </span>
                  <span className="user-meta">
                    <strong> $88K</strong> earned
                  </span>
                </p>
              </div>

              <div className="card__actions">
                <Button size="default" type="white">
                  View Profile
                </Button>
                <Button size="default" type="white">
                  Message
                </Button>
              </div>
            </figcaption>
          </figure>
        </Cards>
      </div>
    </UserCard>
  );
};

UserCardList.propTypes = {
  user: PropTypes.object,
};

export default UserCardList;
