// hexa 8$/hexadash-vue/full-version/src/view/apps/users/overview/work.vue
<template>
  <a-row justify="center">
    <a-col :xl="10" :md="16" :xs="24">
      <div class="user-work-form">
        <BasicFormWrapper>
          <a-form
            style="width: 100%"
            name="work"
            :model="formState"
            :rules="rules"
            @finish="handleFinish"
            @finishFailed="handleFinishFailed"
            :layout="formState.layout"
          >
            <sdHeading class="form-title" as="h4"> Work Information </sdHeading>

            <a-form-item name="company" label="Company Name">
              <a-input
                v-model:value="formState.company"
                placeholder="Company Name"
              />
            </a-form-item>

            <a-form-item name="department" label="Department">
              <a-input
                v-model:value="formState.department"
                placeholder="Department name"
              />
            </a-form-item>

            <a-form-item name="designation" label="Designation">
              <a-input
                v-model:value="formState.designation"
                placeholder="Designation"
              />
            </a-form-item>

            <a-form-item name="hiringDate" label="Hiring Date">
              <a-datePicker
                v-model:value="formState.hiringDate"
                :format="dateFormat"
                style="width: 100%"
              />
            </a-form-item>

            <a-form-item name="status" label="Status" class="work-status">
              <a-radio-group v-model:value="formState.status">
                <a-radio value="active">Active</a-radio>
                <a-radio value="deactivated">Deactivated</a-radio>
                <a-radio value="blocked">Blocked</a-radio>
              </a-radio-group>
            </a-form-item>
            <a-form-item>
              <div class="add-user-bottom text-right">
                <sdButton class="ant-btn ant-btn-light" type="default">
                  Reset
                </sdButton>
                <sdButton htmlType="submit" type="primary">
                  <router-link to="social">Next</router-link>
                </sdButton>
              </div>
            </a-form-item>
          </a-form>
        </BasicFormWrapper>
      </div>
    </a-col>
  </a-row>
</template>
<script>
import { BasicFormWrapper } from "../../../styled";
import { ref, reactive, defineComponent } from "vue";
const dateFormat = "MM/DD/YYYY";

const Work = defineComponent({
  name: "Work",
  components: { BasicFormWrapper },
  setup() {
    const values = ref("");
    const formState = reactive({
      company: "",
      department: "",
      designation: "",
      hiringDate: "",
      status: "active",
      layout: "vertical",
    });

    const rules = {};

    const handleFinish = (values) => {
      values.value = values;
    };

    const handleFinishFailed = (errors) => {
      console.log(errors);
    };

    return {
      values,
      dateFormat,
      formState,
      rules,
      handleFinish,
      handleFinishFailed,
    };
  },
});

export default Work;
</script>

// hexa 8$/hexadash-react/documentation/src/container/pages/overview/work.js
import React, { useState } from 'react';
import { Row, Col, Form, Input, DatePicker, Radio } from 'antd';
import { Link } from 'react-router-dom';
import { BasicFormWrapper } from '../../styled';
import { Button } from '../../../components/buttons/buttons';
import Heading from '../../../components/heading/heading';

const dateFormat = 'MM/DD/YYYY';

const Work = () => {
  const [form] = Form.useForm();
  const [state, setState] = useState({
    values: '',
  });
  const handleSubmit = values => {
    setState({ ...state, values });
  };

  return (
    <Row justify="center">
      <Col xxl={10} xl={14} md={16} xs={24}>
        <div className="user-work-form">
          <BasicFormWrapper>
            <Form style={{ width: '100%' }} form={form} name="work" onFinish={handleSubmit}>
              <Heading className="form-title" as="h4">
                Work Information
              </Heading>

              <Form.Item name="company" label="Company Name">
                <Input placeholder="Company Name" />
              </Form.Item>

              <Form.Item name="department" label="Department">
                <Input placeholder="Department name" />
              </Form.Item>

              <Form.Item name="designation" label="Designation">
                <Input placeholder="Designation" />
              </Form.Item>

              <Form.Item name="hiringDate" rules={[{ type: 'object', whitespace: true }]} label="Hiring Date">
                <DatePicker format={dateFormat} style={{ width: '100%' }} />
              </Form.Item>

              <Form.Item name="status" initialValue="active" label="Status">
                <Radio.Group>
                  <Radio value="active">Active</Radio>
                  <Radio value="deactivated">Deactivated</Radio>
                  <Radio value="blocked">Blocked</Radio>
                </Radio.Group>
              </Form.Item>
              <Form.Item>
                <div className="add-user-bottom text-right">
                  <Button
                    className="ant-btn ant-btn-light"
                    type="default"
                    onClick={() => {
                      return form.resetFields();
                    }}
                  >
                    Reset
                  </Button>
                  <Button htmlType="submit" type="primary">
                    <Link to="/admin/users/add-user/social">Next</Link>
                  </Button>
                </div>
              </Form.Item>
            </Form>
          </BasicFormWrapper>
        </div>
      </Col>
    </Row>
  );
};

export default Work;
