// hexa 8$/hexadash-vue/full-version/src/view/forms/overview/VerticalForm.vue
<template>
  <BasicFormWrapper>
    <VerticalFormStyleWrap>
      <sdCards title="Vertical Form">
        <a-form name="ninjadash_vertical-form" :layout="formState.layout">
          <a-form-item label="Name">
            <a-input value="Duran Clayton" placeholder="input placeholder" />
          </a-form-item>
          <a-form-item label="Email Address">
            <a-input
              name="email"
              value="username@email.com"
              placeholder="input placeholder"
            />
          </a-form-item>
          <a-form-item label="Password">
            <a-input-password
              name="password"
              value="12345678"
              placeholder="with input password"
            />
          </a-form-item>
          <a-row>
            <a-col :xs="24">
              <div class="ninjadash_form-action">
                <sdButton class="btn-signin" html-type="submit" type="light">
                  Cancel
                </sdButton>
                <sdButton class="btn-signin" type="primary"> Save </sdButton>
              </div>
            </a-col>
          </a-row>
        </a-form>
      </sdCards>
    </VerticalFormStyleWrap>
  </BasicFormWrapper>
</template>

<script>
import { VerticalFormStyleWrap } from "./Style";
import { BasicFormWrapper } from "../../styled";
import { defineComponent, reactive } from "vue";
export default defineComponent({
  name: "VerticalForm",
  components: {
    BasicFormWrapper,
    VerticalFormStyleWrap,
  },
  setup() {
    const formState = reactive({
      layout: "vertical",
    });
    return {
      formState,
    };
  },
});
</script>

// hexa 8$/hexadash-react/documentation/src/container/forms/overview/VerticalForm.js
import { Button, Form, Input } from 'antd';
import Prism from "prismjs";
import { useEffect } from 'react';
import { Cards } from '../../../components/cards/frame/cards-frame';
import { BasicFormWrapper } from '../../styled';
import { VerticalFormStyleWrap } from './Style';

const VerticalForm = () => {
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <BasicFormWrapper>
      <VerticalFormStyleWrap>
        <Cards title="Vertical Form">
          <Form name="ninjadash-vertical-form" layout="vertical">
            <Form.Item name="name" initialValue="Duran Clayton" label="Name">
              <Input />
            </Form.Item>
            <Form.Item name="email" initialValue="username@email.com" label="Email Address">
              <Input placeholder="Enter Email" />
            </Form.Item>
            <Form.Item name="password" initialValue="1234567" label="Password">
              <Input.Password />
            </Form.Item>
            <div className="ninjadash-form-action">
              <Button className="btn-signin" htmlType="submit" type="light" size="large">
                Cancel
              </Button>
              <Button className="btn-signin" type="primary" size="large">
                Save
              </Button>
            </div>
          </Form>
          <div className="docs-highlighter mt-35">
                        <pre>
                            <code className="language-javascript">
{
`
import { Form, Input, Button } from 'antd';
import { VerticalFormStyleWrap } from './Style';
import { BasicFormWrapper } from '../../styled';

const VerticalForm = () => {
  return (
    <Form name="ninjadash-vertical-form" layout="vertical">
      <Form.Item name="name" initialValue="Duran Clayton" label="Name">
        <Input />
      </Form.Item>
      <Form.Item name="email" 
        initialValue="username@email.com" 
        label="Email Address">
        <Input placeholder="Enter Email" />
      </Form.Item>
      <Form.Item name="password" initialValue="1234567" label="Password">
        <Input.Password />
      </Form.Item>
      <div className="ninjadash-form-action">
        <Button className="btn-signin" htmlType="submit" type="light" size="large">
          Cancel
        </Button>
        <Button className="btn-signin" type="primary" size="large">
          Save
        </Button>
      </div>
    </Form>
  );
};
export { VerticalForm };
`
}
                            </code>
                        </pre>
                    </div>
        </Cards>
      </VerticalFormStyleWrap>
    </BasicFormWrapper>
  );
};

export { VerticalForm };
