// hexa 8$/hexadash-react/documentation/src/components/charts/DoughnutChart.js
/* eslint-disable react/destructuring-assignment */
import React from 'react';
import PropTypes from 'prop-types';
import DashboardChart from './DashboardChart';

const DoughnutChart = ({ datasets, tooltip, ...props }) => {
  return (
    <div className="doughnutchart-inner">
      <div className="doughnutchart-inner-text">
        {datasets[0].centerText === '' ? (
          <span className="doughnutchart-inner-content">{datasets[0].data.reduce((a, b) => a + b, 0)}%</span>
        ) : (
          <span className="doughnutchart-inner-content">{datasets[0].centerText}</span>
        )}
        <span className="doughnutchart-inner-label">{datasets[0].centerTextLabel}</span>
      </div>

      <DashboardChart tooltip={tooltip} type="doughnut" datasets={datasets} {...props} />
    </div>
  );
};

DoughnutChart.defaultProps = {
  height: 479,
  width: 250,
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  datasets: [
    {
      data: [20, 60, 50, 45, 50, 60, 70, 40, 45, 35, 25, 30],
      borderColor: '#001737',
      borderWidth: 1,
      fill: false,
    },
    {
      data: [10, 40, 30, 40, 60, 55, 45, 35, 30, 20, 15, 20],
      borderColor: '#1ce1ac',
      borderWidth: 1,
      fill: false,
    },
  ],
  layout: {},
  legend: {
    display: false,
    labels: {
      display: false,
    },
  },
  id: 'myChart',
  elements: {
    line: {
      tension: 0.5,
      borderCapStyle: 'round',
      borderJoinStyle: 'round',
      capBezierPoints: true,
    },
    point: {
      radius: 0,
      z: 5,
    },
  },

  scales: {
    y: {
      display: false,
    },
    x: {
      display: false,
    },
  },

  tooltip: {},
  option: {
    borderColor: ({ theme }) => theme[theme.mainContent]['white-background']
  },
};

DoughnutChart.propTypes = {
  height: PropTypes.number,
  labels: PropTypes.arrayOf(PropTypes.string),
  datasets: PropTypes.arrayOf(PropTypes.object),
  id: PropTypes.string,
  legend: PropTypes.object,
  layout: PropTypes.object,
  elements: PropTypes.object,
  scales: PropTypes.object,
  tooltip: PropTypes.object,
  option: PropTypes.object,
};

export default DoughnutChart;

// hexa 8$/hexadash-vue/full-version/src/components/utilities/DoughnutChart.vue
<template>
  <div class="doughnutchart-inner">
    <div class="doughnutchart-inner-text">
      <span
        v-if="datasets[0].centerText === ''"
        class="doughnutchart-inner-content"
        >{{ datasets[0].data.reduce((a, b) => a + b, 0) }}%</span
      >

      <span v-else class="doughnutchart-inner-content">{{
        datasets[0].centerText
      }}</span>

      <span class="doughnutchart-inner-label">{{
        datasets[0].centerTextLabel
      }}</span>
    </div>

    <DashboardChart
      :tooltip="tooltip"
      type="doughnut"
      :datasets="datasets"
      :id="id"
      :className="className"
      :labels="labels"
      :height="height"
      :options="options"
      :legend="legend"
      :layout="layout"
      :elements="elements"
      :scales="scales"
    />
  </div>
</template>
<script>
import { defineComponent } from "vue";
import PropTypes from "vue-types";
import DashboardChart from "./chartjs.vue";

export default defineComponent({
  components: {
    DashboardChart,
  },
  props: {
    height: PropTypes.number.def(479),
    labels: PropTypes.arrayOf(PropTypes.string).def([
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ]),
    datasets: PropTypes.arrayOf(PropTypes.object).def([
      {
        data: [20, 60, 50, 45, 50, 60, 70, 40, 45, 35, 25, 30],
        borderColor: "#001737",
        borderWidth: 1,
        fill: false,
      },
      {
        data: [10, 40, 30, 40, 60, 55, 45, 35, 30, 20, 15, 20],
        borderColor: "#1ce1ac",
        borderWidth: 1,
        fill: false,
      },
    ]),
    id: PropTypes.string.def("myChart"),
    className: PropTypes.string.def("myChart"),
    legend: PropTypes.object.def({
      display: false,
      labels: {
        display: false,
      },
    }),
    layout: PropTypes.object.def({}),
    elements: PropTypes.object.def({
      line: {
        tension: 0.5,
        borderCapStyle: "round",
        borderJoinStyle: "round",
        capBezierPoints: true,
      },
      point: {
        radius: 0,
        z: 5,
      },
    }),
    scales: PropTypes.object.def({
      y: {
        display: false,
      },
      x: {
        display: false,
      },
    }),
    tooltip: PropTypes.object.def({}),
    options: PropTypes.object.def({}),
  },
  setup() {},
});
</script>
