// hexa 8$/hexadash-vue/full-version/src/view/pages/Maintenance.vue
<template>
  <div>
    <Main>
      <MaintananceWrapper>
        <img :src="require(`../../static/img/pages/maintenance.svg`)" alt="maintenance" />
        <sdHeading as="h3">We are currently performing maintenance</sdHeading>
        <p>
          We&rsquo;re making the system more awesome. <br />
          We&rsquo;ll be back shortly.
        </p>
      </MaintananceWrapper>
    </Main>
  </div>
</template>

<script>
import { Main } from '../styled';
import { MaintananceWrapper } from './style';
import { defineComponent } from 'vue';
export default defineComponent({
  name: 'Maintenance',
  components: {
    Main,
    MaintananceWrapper,
  },
  data() {
    return {};
  },
});
</script>

// hexa 8$/hexadash-svelte/hexadash/src/routes/(common-layout)/pages/maintenance/+page.svelte
<script>
	import { Container, Row, Col } from 'sveltestrap';
</script>

<svelte:head>
	<title>Gallery</title>
</svelte:head>

<div class="component-page mb-25">
	<Container fluid>
		<Row>
			<Col lg={12}>
				<div class="maintenance-wrapper content-center">
					<div class="maintenance-page text-center">
						<img class="svg" alt="" src={'/img/svg/maintenance.svg'} />
						<h5 class="maintenance-page__title">We are currently performing maintenance</h5>
						<p class="fw-500">We're making the system more awesome.We'll be back shortly.</p>
					</div>
				</div>
			</Col>
		</Row>
	</Container>
</div>

<style lang="scss">
	.maintenance-wrapper {
		height: calc(100vh - 169px);
	}
	.maintenance-page__title {
		font-weight: 500;
		margin: 70px 0 14px;
	}

	.maintenance-page p {
		font-size: 14px;
		color: var(--color-gray);
	}

	:global {
		.maintenance-page svg {
			max-width: 100%;
			height: auto;
		}
	}
</style>
