// hexa 8$/hexadash-react/documentation/src/components/cards/ProfileCard.js
import React from 'react';
import { Link } from 'react-router-dom';
import FontAwesome from 'react-fontawesome';
import propTypes from 'prop-types';
import { ProfileCardWrapper } from './Style';

const ProfileCard = ({ image, bgImage, title, tag }) => {
  return (
    <ProfileCardWrapper>
      <figcaption>
        <img className="ninjadash-profile-top-img" src={require(`../../${bgImage}`)} alt="banner" />
        <div className="ninjadash-profile-content">
          <div className="ninjadash-profile-content__img">
            <img className="profile" src={require(`../../${image}`)} alt="profile" />
          </div>
          <h4 className="ninjadash-profile-name">{title}</h4>
          <p className="ninjadash-profile-text">{tag}</p>
          <ul className="ninjadash-profile-socials">
            <li className="ninjadash-facebook">
              <Link to="#">
                <FontAwesome name="facebook" />
              </Link>
            </li>
            <li className="ninjadash-twitter">
              <Link to="#">
                <FontAwesome name="twitter" />
              </Link>
            </li>
            <li className="ninjadash-dribble">
              <Link to="#">
                <FontAwesome name="dribbble" />
              </Link>
            </li>
          </ul>
        </div>
      </figcaption>
    </ProfileCardWrapper>
  );
};

ProfileCard.propTypes = {
  image: propTypes.string,
  bgImage: propTypes.string,
  title: propTypes.string,
  tag: propTypes.string,
};

ProfileCard.defaultProps = {
  image: 'static/img/users/1.png',
  bgImage: 'static/img/banner/BG.png',
  title: 'Robert Clinton',
  tag: 'Best Seller of the last month',
};

export default ProfileCard;

// hexa 8$/hexadash-typescript-vue/documentation/src/components/cards/ProfileCard.vue
<template>
  <ProfileCardWrapper>
    <figcaption>
      <img
        class="ninjadash-profile-top-img"
        :src="require(`@/${bgImage}`)"
        alt="banner"
      />
      <div class="ninjadash-profile-content">
        <div class="ninjadash-profile-content__img">
          <img class="profile" :src="require(`@/${image}`)" alt="profile" />
        </div>
        <h4 class="ninjadash-profile-name">{{ title }}</h4>
        <p class="ninjadash-profile-text">{{ tag }}</p>
        <ul class="ninjadash-profile-socials">
          <li class="ninjadash-facebook">
            <router-link to="#">
              <font-awesome-icon
                class="super-crazy-colors"
                :icon="faFacebookF"
                size="1x"
                :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
              />
            </router-link>
          </li>
          <li class="ninjadash-twitter">
            <router-link to="#">
              <font-awesome-icon
                class="super-crazy-colors"
                :icon="faTwitter"
                size="1x"
                :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
              />
            </router-link>
          </li>
          <li class="ninjadash-dribble">
            <router-link to="#">
              <font-awesome-icon
                class="super-crazy-colors"
                :icon="faDribbble"
                size="1x"
                :style="{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }"
              />
            </router-link>
          </li>
        </ul>
      </div>
    </figcaption>
  </ProfileCardWrapper>
</template>
<script>
import { defineComponent } from "vue";
import propTypes from "vue-types";
import { ProfileCardWrapper } from "./style";
import {
  faFacebookF,
  faDribbble,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";

export default defineComponent({
  components: { ProfileCardWrapper },
  props: {
    image: propTypes.string.def("static/img/users/1.png"),
    bgImage: propTypes.string.def("static/img/banner/BG.png"),
    title: propTypes.string.def("Robert Clinton"),
    tag: propTypes.string.def("Best Seller of the last month"),
  },
  setup() {
    return {
      faFacebookF,
      faDribbble,
      faTwitter,
    };
  },
});
</script>
