// hexa 8$/hexadash-svelte/hexadash/src/routes/(common-layout)/(apps)/ecommerce/invoice/+page.svelte
<script>
	import BreadcrumbOne from '$lib/components/breadcrumbs/BreadcrumbOne.svelte';
	import { Container, Row, Col, Table } from 'sveltestrap';
    import { PrinterIcon, SendIcon, DownloadIcon } from 'svelte-feather-icons';

	const breadcrumbData = {
		pageTitle: 'Invoice',
		bcItem: 'eCommerce',
		bcItemActive: 'Invoice'
	};


</script>


<Container fluid>
    <Row>
        <Col lg={12}>
            <BreadcrumbOne {...breadcrumbData} />
        </Col>
    </Row>
</Container>

<Container fluid>
    <Row>
        <Col lg={12}>
            <div class="payment-invoice global-shadow border-light-light radius-xl w-100 mb-30">
                <div class="payment-invoice__body">
                    <div class="payment-invoice-address d-flex justify-content-sm-between">
                        <div class="payment-invoice-logo">
                            <a href="/">
                                <img src="/img/logo-dark.svg" alt="">
                            </a>
                        </div>
                        <div class="payment-invoice-address__area">
                            <address>
                                Admin Company<br> 795 Folsom Ave, Suite 600<br> San Francisco, CA 94107, USA<br> Reg. number : 245000003513
                            </address>
                        </div>
                    </div>
                    <div class="payment-invoice-qr d-flex justify-content-between mb-40 px-xl-50 px-30 py-sm-30 py-20">
                        <div class="d-flex justify-content-center mb-lg-0 mb-25">
                            <div class="payment-invoice-qr__number">
                                <div class="display-3">Invoice</div>
                                <p>No : <span>#642678</span></p>
                                <p>Date : <span>Jan 17, 2020</span></p>
                            </div>
                        </div>
                        <div class="d-flex justify-content-center mb-lg-0 mb-25">
                            <div class="payment-invoice-qr__code bg-white radius-xl p-20">
                                <img src="/img/qr.png" alt="">
                                <p>8364297359912267</p>
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            <div class="payment-invoice-qr__address">
                                <p>Invoice To:</p>
                                <span>Stanley Jones</span><br>
                                <span>795 Folsom Ave, Suite 600</span><br>
                                <span>San Francisco, CA 94107, USA</span>
                            </div>
                        </div>
                    </div>
                    <div class="payment-invoice-table">
                        <div class="table-responsive">
                            <Table borderless id="cart" >
                                <thead>
                                    <tr class="product-cart__header">
                                        <th scope="col">#</th>
                                        <th scope="col">Product</th>
                                        <th scope="col" class="text-end">Price Per Unit</th>
                                        <th scope="col" class="text-end">Quantity</th>
                                        <th scope="col" class="text-end">Order Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td class="Product-cart-title">
                                            <div class="media  align-items-center">
                                                <div class="media-body">
                                                    <h5 class="mt-0">Fiber base chair</h5>
                                                    <div class="d-flex">
                                                        <p>Size:<span>large</span></p>
                                                        <p>color:<span>brown</span></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="unit text-end">$248.66</td>
                                        <td class="invoice-quantity text-end">1</td>
                                        <td class="text-end order">$5.11</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td class="Product-cart-title">
                                            <div class="media  align-items-center">
                                                <div class="media-body">
                                                    <h5 class="mt-0">Plastic chair</h5>
                                                    <div class="d-flex">
                                                        <p>Size:<span>large</span></p>
                                                        <p>color:<span>brown</span></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="unit text-end">$248.66</td>
                                        <td class="invoice-quantity text-end">2</td>
                                        <td class="text-end order">$5.11</td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="3"></td>
                                        <td class="order-summery float-right border-0   ">
                                            <div class="total">
                                                <div class="subtotalTotal mb-0 text-end">Subtotal : </div>
                                                <div class="taxes mb-0 text-end">discount : </div>
                                                <div class="shipping mb-0 text-end">Shipping charge :</div>
                                            </div>
                                            <div class="total-money mt-2 text-end">
                                                <h6>Total :</h6>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="total-order float-right text-end fs-14 fw-500">
                                                <p>$1,690.26</p>
                                                <p>-$126.30</p>
                                                <p>$46.30</p>
                                                <h5 class="color-primary">$1736.00</h5>
                                            </div>
                                        </td>
                                    </tr>
                                </tfoot>
                            </Table>
                        </div>
                    </div>
                    <div class="payment-invoice__btn mt-xxl-50 pt-xxl-30">
                        <button class="btn border rounded-pill bg-normal text-gray px-25 print-btn"><PrinterIcon /> Print</button>
                        <button class="btn border rounded-pill bg-normal text-gray px-25 print-btn"><SendIcon /> Invoice</button>
                        <button class="btn-primary btn rounded-pill px-25 text-white download"><DownloadIcon /> Download</button>
                    </div>
                </div>
            </div>
        </Col>
    </Row>
</Container>
<style lang="scss">
	:global{
		@import "../../../../../assets/sass/mixins/functions";
		@import "../../../../../assets/sass/mixins/rfs";
		@import "../../../../../assets/sass/mixins/media-queries";
		@import "../../../../../assets/sass/components/cart";
		@import "../../../../../assets/sass/components/checkout";
	}
</style>

// hexa 8$/hexadash-vue/full-version/src/view/apps/ecommerce/Invoice.vue
<template>
  <sdPageHeader title="Invoice" class="ninjadash-page-header-main">
  </sdPageHeader>
  <Main>
    <a-row :gutter="15">
      <a-col :md="24">
        <sdCards headless>
          <InvoiceHeader>
            <a-row>
              <a-col :sm="12" :xs="24">
                <figure>
                  <img
                    class="top-img"
                    :src="
                      !darkMode
                        ? require('@/static/img/Logo_Dark.svg')
                        : require('@/static/img/Logo_White.svg')
                    "
                    alt="logo"
                  />
                </figure>
              </a-col>
              <a-col :sm="12" :xs="24">
                <div>
                  <address class="invoice-info">
                    Admin Company <br />
                    795 Folsom Ave, Suite 600 <br />
                    San Francisco, CA 94107, USA <br />
                    Reg. number : 245000003513
                  </address>
                </div>
              </a-col>
            </a-row>
          </InvoiceHeader>
          <InvoiceLetterBox>
            <div class="invoice-letter-inner">
              <a-row align="middle">
                <a-col :lg="8" :xs="24">
                  <article class="invoice-author">
                    <sdHeading class="invoice-author__title" as="h3">
                      Invoice
                    </sdHeading>
                    <p>No : #642678</p>
                    <p>Date : Jan 17, 2021</p>
                  </article>
                </a-col>
                <a-col :lg="8" :xs="24">
                  <div class="invoice-barcode">
                    <sdCards class="invoice-card" headless>
                      <img
                        style="width: 100%"
                        :src="require('@/static/img/barcode.png')"
                        alt="barcode"
                      />
                      <p>8364297359912267</p>
                    </sdCards>
                  </div>
                </a-col>
                <a-col :lg="8" :xs="24">
                  <address class="invoice-customer">
                    <sdHeading class="invoice-customer__title" as="h5">
                      Invoice To:
                    </sdHeading>
                    <p>
                      Stanley Jones <br />
                      795 Folsom Ave, Suite 600 <br />
                      San Francisco, CA 94107, USA
                    </p>
                  </address>
                </a-col>
              </a-row>
            </div>
          </InvoiceLetterBox>

          <br />
          <br />
          <ProductTable>
            <div class="table-invoice table-responsive">
              <a-table
                :dataSource="invoiceTableData"
                :columns="invoiceTableColumns"
                :pagination="false"
              />
            </div>
          </ProductTable>

          <a-row justify="end">
            <a-col :xxl="4" :xl="5" :sm="8" :xs="14" :offset="rtl ? 0 : 10">
              <OrderSummary>
                <div class="invoice-summary-inner">
                  <ul class="summary-list">
                    <li>
                      <span class="summary-list-title">Subtotal :</span>
                      <span class="summary-list-text">{{ `$${497.32}` }}</span>
                    </li>
                    <li>
                      <span class="summary-list-title">Discount :</span>
                      <span class="summary-list-text">{{ `$${-20}` }}</span>
                    </li>
                    <li>
                      <span class="summary-list-title">Shipping Charge :</span>
                      <span class="summary-list-text">{{ `$${30}` }}</span>
                    </li>
                  </ul>
                  <sdHeading class="summary-total" as="h4">
                    <span class="summary-total-label">Total : </span>
                    <span class="summary-total-amount">{{ `$${507.32}` }}</span>
                  </sdHeading>
                </div>
              </OrderSummary>
            </a-col>
          </a-row>
          <a-row justify="end">
            <a-col :lg="12" :md="18" :sm="24" :offset="0">
              <InvoiceAction>
                <sdButton size="sm" shape="round" type="default">
                  <unicon name="print" width="14"></unicon>
                  <span>Print</span>
                </sdButton>
                <sdButton size="sm" shape="round" type="default">
                  <unicon name="message" width="14"></unicon>
                  <span>Send Invoice</span>
                </sdButton>
                <sdButton size="sm" shape="round" type="primary">
                  <unicon name="import" width="14"></unicon>
                  <span>Download</span>
                </sdButton>
              </InvoiceAction>
            </a-col>
          </a-row>
        </sdCards>
      </a-col>
    </a-row>
  </Main>
</template>
<script>
import {
  InvoiceHeader,
  InvoiceLetterBox,
  InvoiceAction,
  ProductTable,
  OrderSummary,
} from "./Style";
import { Main } from "../../styled";
import { useStore } from "vuex";
import { computed, defineComponent } from "vue";

const Invoice = defineComponent({
  name: "Invoice",
  components: {
    InvoiceHeader,
    InvoiceLetterBox,
    InvoiceAction,
    ProductTable,
    OrderSummary,
    Main,
  },
  setup() {
    const { state } = useStore();
    const rtl = computed(() => state.themeLayout.rtlData);
    const darkMode = computed(() => state.themeLayout.data);
    return {
      rtl,
      darkMode,
      invoiceTableData: [
        {
          key: "1",
          row: "1",
          details: (
            <div>
              <div class="product-info">
                <sdHeading class="product-info-title" as="h6">
                  Fiber Base Chair
                </sdHeading>
                <ul class="info-list">
                  <li>
                    <span class="info-title">Size :</span>
                    <span>Large</span>
                  </li>
                  <li>
                    <span class="info-title"> Color :</span>
                    <span>Brown</span>
                  </li>
                </ul>
              </div>
            </div>
          ),
          unit: <span class="product-unit">$248.66</span>,
          quantity: <span class="product-quantity">3</span>,
          total: <span class="product-total-price">$943.30</span>,
        },
        {
          key: "2",
          row: "2",
          details: (
            <div>
              <div class="product-info">
                <sdHeading class="product-info-title" as="h6">
                  Panton Tunior Chair
                </sdHeading>
                <ul class="info-list">
                  <li>
                    <span class="info-title">Size :</span>
                    <span>Large</span>
                  </li>
                  <li>
                    <span class="info-title"> Color :</span>
                    <span>Brown</span>
                  </li>
                </ul>
              </div>
            </div>
          ),
          unit: <span class="product-unit">$248.66</span>,
          quantity: <span class="product-quantity">2</span>,
          total: <span class="product-total-price">$943.30</span>,
        },
      ],
      invoiceTableColumns: [
        {
          title: "#",
          dataIndex: "row",
          key: "row",
        },
        {
          title: "Product Details",
          dataIndex: "details",
          key: "details",
        },
        {
          title: "Price Per Unit",
          dataIndex: "unit",
          key: "unit",
        },
        {
          title: "Quantity",
          dataIndex: "quantity",
          key: "quantity",
        },
        {
          title: "Order Total",
          dataIndex: "total",
          key: "total",
        },
      ],
    };
  },
});

export default Invoice;
</script>
