// hexa 8$/hexadash-react/documentation/src/container/table/DataTable.js
import UilEdit from '@iconscout/react-unicons/icons/uil-edit';
import UilEye from '@iconscout/react-unicons/icons/uil-eye';
import UilTrash from '@iconscout/react-unicons/icons/uil-trash-alt';
import { Col, Row } from 'antd';
import Prism from "prismjs";
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { Cards } from '../../components/cards/frame/cards-frame';
import { PageHeader } from '../../components/page-headers/page-headers';
import DataTable from '../../components/table/DataTable';
import { tableReadData } from '../../redux/data-filter/actionCreator';
import { BorderLessHeading, Main } from '../styled';

const DataTables = () => {
  const dispatch = useDispatch();

  const PageRoutes = [
    {
      path: 'index',
      breadcrumbName: 'Dashboard',
    },
    {
      path: 'first',
      breadcrumbName: 'Table',
    },
  ];

  useEffect(() => {
    if (dispatch) {
      dispatch(tableReadData())
    }
    Prism.highlightAll();
  }, [dispatch]);

  const { TableData } = useSelector(state => {
      return {
          TableData: state.dataTable.tableData
      };
  });

  const tableDataScource = [];

  if(TableData.length >0){
    TableData.map(item => {
      const { id, name, country, company, position, status, date } = item;
      return tableDataScource.push({
        key: id,
        id: `#${id}`,
        user: (
          <span className="ninjadash-username">{name}</span>
        ),
        country: (
          <span>{country}</span>
        ),
        company: (
          <span>{company}</span>
        ),
        position,
        date,
        status: (
          <span className={`ninjadash-status ninjadash-status-${status}`}>{status}</span>
        ),
        action: (
          <div className="table-actions">
            <Link className="view" to={`#`}>
              <UilEye />
            </Link>
            <Link className="edit" to="#"><UilEdit /></Link>
            <Link className="delete" to="#">
              <UilTrash />
            </Link>
          </div>
        ),
      });
    });
  }

  const dataTableColumn = [
    {
      title: 'Id',
      dataIndex: 'id',
      key: 'id',
    },
    {
      title: 'User',
      dataIndex: 'user',
      key: 'user',
    },
    {
      title: 'Country',
      dataIndex: 'country',
      key: 'coutry',
    },
    {
      title: 'Company',
      dataIndex: 'company',
      key: 'company',
    },
    {
      title: 'Position',
      dataIndex: 'position',
      key: 'position',
    },
    {
      title: 'Join Date',
      dataIndex: 'date',
      key: 'date',
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
    },
    {
      title: 'Actions',
      dataIndex: 'action',
      key: 'action',
      width: '90px',
    },
  ]

  return (
    <>
      <PageHeader className="ninjadash-page-header-main" title="Table" routes={PageRoutes} />
      <Main>
        <Row gutter={15}>
          <Col xs={24}>
            <BorderLessHeading>
              <Cards title="Data Table">
                <DataTable filterOption filterOnchange={true} tableData={ tableDataScource } columns={dataTableColumn} rowSelection={false}/>
                <div className="docs-highlighter mt-35">
                        <pre>
                            <code className="language-javascript">
{
`
import React from 'react';
import { Main } from '../styled';

const tableDataScource = [];

const dataTableColumn = [
  {
    title: 'Id',
    dataIndex: 'id',
    key: 'id',
  },
  {
    title: 'User',
    dataIndex: 'user',
    key: 'user',
  },
  {
    title: 'Country',
    dataIndex: 'country',
    key: 'coutry',
  },
  {
    title: 'Company',
    dataIndex: 'company',
    key: 'company',
  },
  {
    title: 'Position',
    dataIndex: 'position',
    key: 'position',
  },
  {
    title: 'Join Date',
    dataIndex: 'date',
    key: 'date',
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: 'Actions',
    dataIndex: 'action',
    key: 'action',
    width: '90px',
  },
]

const DataTables = () => {
  return (
    <Main>
      <DataTable filterOption filterOnchange={true} tableData={ tableDataScource } columns={dataTableColumn} rowSelection={true}/>
    </Main>
  );
};

export default DataTables;
`
}
                            </code>
                        </pre>
                    </div>
              </Cards>
            </BorderLessHeading>
          </Col>
          <Col xs={24}>
            <BorderLessHeading>
              <Cards title="Data Table 2">
                <DataTable filterOption filterOnchange={true} tableData={ tableDataScource } columns={dataTableColumn} rowSelection={true}/>
                <div className="docs-highlighter mt-35">
                        <pre>
                            <code className="language-javascript">
{
`
import React from 'react';
import { Main } from '../styled';

const tableDataScource = [];

const dataTableColumn = [
  {
    title: 'Id',
    dataIndex: 'id',
    key: 'id',
  },
  {
    title: 'User',
    dataIndex: 'user',
    key: 'user',
  },
  {
    title: 'Country',
    dataIndex: 'country',
    key: 'coutry',
  },
  {
    title: 'Company',
    dataIndex: 'company',
    key: 'company',
  },
  {
    title: 'Position',
    dataIndex: 'position',
    key: 'position',
  },
  {
    title: 'Join Date',
    dataIndex: 'date',
    key: 'date',
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: 'Actions',
    dataIndex: 'action',
    key: 'action',
    width: '90px',
  },
]

const DataTables = () => {
  return (
    <Main>
      <DataTable filterOption filterOnchange={true} tableData={ tableDataScource } columns={dataTableColumn} rowSelection={true}/>
    </Main>
  );
};

export default DataTables;
`
}
                            </code>
                        </pre>
                    </div>
              </Cards>
            </BorderLessHeading>
          </Col>
        </Row>
      </Main>
    </>
  );
};

export default DataTables;

// hexa 8$/hexadash-typescript-vue/documentation/src/view/pages/Table/DataTable.vue
<template>
  <div>
    <sdPageHeader
      title="Table"
      class="ninjadash-page-header-main"
      :routes="PageRoutes"
    >
    </sdPageHeader>
    <Main>
      <DocumentationStyleWrap>
        <a-row :gutter="25">
          <a-col :sm="24" :xs="24">
            <sdCards title="Data Table">
              <DataTable
                :filterOption="true"
                :filterOnchange="true"
                :tableData="tableData"
                :columns="dataTableColumn"
                :rowSelection="true"
              />
              <br />
              <prism-editor
                :readonly="false"
                class="my-editor height-100 mb-35"
                v-model="auth0Env"
                :highlight="highlighter"
              ></prism-editor>
            </sdCards>
          </a-col>
        </a-row>
      </DocumentationStyleWrap>
    </Main>
  </div>
</template>

<script>
import { Main } from "../../styled";
import { computed, defineComponent, onMounted, ref } from "vue";
import { DocumentationStyleWrap } from "../style";
import { useStore } from "vuex";
import DataTable from "@/components/table/DataTable";

import { PrismEditor } from "vue-prism-editor";
import "vue-prism-editor/dist/prismeditor.min.css";
import { highlight, languages } from "prismjs/components/prism-core";
import "prismjs/components/prism-clike";
import "prismjs/components/prism-javascript";
import "prismjs/themes/prism-tomorrow.css";

const dataTableColumn = [
  {
    title: "Id",
    dataIndex: "id",
    key: "id",
  },
  {
    title: "User",
    dataIndex: "user",
    key: "user",
  },
  {
    title: "Country",
    dataIndex: "country",
    key: "coutry",
  },
  {
    title: "Company",
    dataIndex: "company",
    key: "company",
  },
  {
    title: "Position",
    dataIndex: "position",
    key: "position",
  },
  {
    title: "Join Date",
    dataIndex: "date",
    key: "date",
  },
  {
    title: "Status",
    dataIndex: "status",
    key: "status",
  },
  {
    title: "Actions",
    dataIndex: "action",
    key: "action",
    width: "90px",
  },
];

const PageRoutes = [
  {
    path: "index",
    breadcrumbName: "Docs",
  },
  {
    path: "",
    breadcrumbName: "Data Table",
  },
];

export default defineComponent({
  name: "Basic Table",
  components: {
    Main,
    DocumentationStyleWrap,
    PrismEditor,
    DataTable,
  },
  setup() {
    const { state, dispatch } = useStore();

    const tableData = computed(() =>
      state.dataTable.tableData.map((item) => {
        const { id, name, country, company, position, status, date } = item;
        return {
          key: id,
          id: `#${id}`,
          user: <span class="ninjadash-username">{name}</span>,
          country: <span>{country}</span>,
          company: <span>{company}</span>,
          position,
          date,
          status: (
            <span class={`ninjadash-status ninjadash-status-${status}`}>
              {status}
            </span>
          ),
          action: (
            <div class="table-actions">
              <router-link class="view" to={`#`}>
                <unicon name="eye" />
              </router-link>
              <router-link class="edit" to="#">
                <unicon name="edit" />
              </router-link>
              <router-link class="delete" to="#">
                <unicon name="trash" />
              </router-link>
            </div>
          ),
        };
      })
    );

    onMounted(() => dispatch("tableReadData"));

    const auth0Env = ref(`    
<template>
  <Main>
    <DataTable
      :filterOption="true"
      :filterOnchange="true"
      :tableData="tableData"
      :columns="dataTableColumn"
      :rowSelection="true"
    />
  </Main>
</template>

<script>
  import { defineComponent, ref } from "vue";
  import { Main } from '../styled';
  import DataTable from "@/components/table/DataTable";


  const tableDataScource = [];

  const dataTableColumn = [
    {
      title: 'Id',
      dataIndex: 'id',
      key: 'id',
    },
    {
      title: 'User',
      dataIndex: 'user',
      key: 'user',
    },
    {
      title: 'Country',
      dataIndex: 'country',
      key: 'coutry',
    },
    {
      title: 'Company',
      dataIndex: 'company',
      key: 'company',
    },
    {
      title: 'Position',
      dataIndex: 'position',
      key: 'position',
    },
    {
      title: 'Join Date',
      dataIndex: 'date',
      key: 'date',
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
    },
    {
      title: 'Actions',
      dataIndex: 'action',
      key: 'action',
      width: '90px',
    },
  ]

  export default defineComponent({    
    components: {
      Main,
      DataTable
    },
    setup() {
      return {
        tableDataScource,
        dataTableColumn
      }
    }
  });
< /script>
`);

    return {
      PageRoutes,
      auth0Env,
      dataTableColumn,
      tableData,
    };
  },
  methods: {
    highlighter(code) {
      return highlight(code, languages.js); //returns html
    },
  },
});
</script>
